import type { PoolConnection, RowDataPacket } from "mysql2/promise";
import { selectOne, selectRows } from "@/lib/db/query";
import type { QuoteInput } from "./validation";

export type CommerceErrorCode = "CART_CHANGED" | "OUT_OF_STOCK" | "INVALID_COUPON" | "COUPON_LIMIT" | "DELIVERY_UNAVAILABLE";
export class CommerceError extends Error { constructor(public readonly code: CommerceErrorCode, message: string) { super(message); this.name = "CommerceError"; } }

interface ProductRow extends RowDataPacket { product_id: string; variant_id: string; slug: string; product_name: string; variant_title: string; sku: string; price_pence: number; stock_on_hand: number; track_inventory: number; image_url: string | null; category_ids: string | null; collection_ids: string | null }
interface DiscountRow extends RowDataPacket { id: string; name: string; method: "AUTOMATIC" | "COUPON"; discount_type: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_SHIPPING"; value: number; applies_to: "ALL" | "PRODUCTS" | "CATEGORIES" | "COLLECTIONS"; minimum_subtotal_pence: number | null; maximum_discount_pence: number | null; coupon_id: string | null; coupon_code: string | null; usage_limit: number | null; per_email_limit: number | null; used_count: number; product_ids: string | null; category_ids: string | null; collection_ids: string | null }
interface ShippingRow extends RowDataPacket { id: string; name: string; method_type: string; price_pence: number; free_over_pence: number | null; estimated_days_min: number | null; estimated_days_max: number | null }
interface CountRow extends RowDataPacket { redemption_count: number }

export interface QuoteLine { productId: string; variantId: string; slug: string; name: string; variantTitle: string; sku: string; image: string | null; unitPricePence: number; quantity: number; subtotalPence: number; discountPence: number; totalPence: number; stockOnHand: number; trackInventory: boolean; categoryIds: string[]; collectionIds: string[] }
export interface CheckoutQuote { lines: QuoteLine[]; subtotalPence: number; discountPence: number; shippingPence: number; taxPence: number; totalPence: number; currency: "GBP"; discount: { id: string; name: string; couponId: string | null; couponCode: string | null; freeShipping: boolean } | null; shippingMethod: { id: string; name: string; estimatedDaysMin: number | null; estimatedDaysMax: number | null }; shippingMethods: { id: string; name: string; pricePence: number; estimatedDaysMin: number | null; estimatedDaysMax: number | null }[] }

const ids = (value: string | null) => value?.split(",").filter(Boolean) ?? [];
function lineEligible(line: QuoteLine, discount: DiscountRow) { if (discount.applies_to === "ALL") return true; const targets = discount.applies_to === "PRODUCTS" ? ids(discount.product_ids) : discount.applies_to === "CATEGORIES" ? ids(discount.category_ids) : ids(discount.collection_ids); const lineValues = discount.applies_to === "PRODUCTS" ? [line.productId] : discount.applies_to === "CATEGORIES" ? line.categoryIds : line.collectionIds; return lineValues.some((id) => targets.includes(id)); }
function discountAmount(discount: DiscountRow, eligibleSubtotal: number) { if (!eligibleSubtotal || discount.discount_type === "FREE_SHIPPING") return 0; let amount = discount.discount_type === "PERCENTAGE" ? Math.floor(eligibleSubtotal * Math.min(discount.value, 100) / 100) : Math.min(discount.value, eligibleSubtotal); if (discount.maximum_discount_pence !== null) amount = Math.min(amount, discount.maximum_discount_pence); return amount; }

export async function calculateQuote(input: QuoteInput, connection?: PoolConnection): Promise<CheckoutQuote> {
  const placeholders = input.items.map(() => "?").join(",");
  const productRows = await selectRows<ProductRow>(`SELECT CAST(p.id AS CHAR) AS product_id, CAST(v.id AS CHAR) AS variant_id, p.slug, p.name AS product_name, v.title AS variant_title, v.sku, v.price_pence, v.stock_on_hand, p.track_inventory, i.url AS image_url, GROUP_CONCAT(DISTINCT pc.category_id) AS category_ids, GROUP_CONCAT(DISTINCT pcl.collection_id) AS collection_ids FROM products p INNER JOIN product_variants v ON v.product_id = p.id AND v.is_default = 1 AND v.status = 'ACTIVE' LEFT JOIN product_images i ON i.id = (SELECT pi.id FROM product_images pi WHERE pi.product_id = p.id ORDER BY pi.sort_order, pi.id LIMIT 1) LEFT JOIN product_categories pc ON pc.product_id = p.id LEFT JOIN product_collections pcl ON pcl.product_id = p.id WHERE p.status = 'ACTIVE' AND p.slug IN (${placeholders}) GROUP BY p.id, v.id, i.url`, input.items.map((item) => item.slug), connection);
  if (productRows.length !== input.items.length) throw new CommerceError("CART_CHANGED", "One or more products are no longer available.");
  const products = new Map(productRows.map((row) => [row.slug, row]));
  const lines: QuoteLine[] = input.items.map((item) => { const row = products.get(item.slug); if (!row) throw new CommerceError("CART_CHANGED", "Product not found."); if (Boolean(row.track_inventory) && row.stock_on_hand < item.quantity) throw new CommerceError("OUT_OF_STOCK", `${row.product_name} does not have enough stock.`); const subtotal = row.price_pence * item.quantity; return { productId: row.product_id, variantId: row.variant_id, slug: row.slug, name: row.product_name, variantTitle: row.variant_title, sku: row.sku, image: row.image_url, unitPricePence: row.price_pence, quantity: item.quantity, subtotalPence: subtotal, discountPence: 0, totalPence: subtotal, stockOnHand: row.stock_on_hand, trackInventory: Boolean(row.track_inventory), categoryIds: ids(row.category_ids), collectionIds: ids(row.collection_ids) }; });
  const subtotalPence = lines.reduce((sum, line) => sum + line.subtotalPence, 0);
  const discounts = await selectRows<DiscountRow>(`SELECT CAST(d.id AS CHAR) AS id, d.name, d.method, d.discount_type, d.value, d.applies_to, d.minimum_subtotal_pence, d.maximum_discount_pence, CAST(c.id AS CHAR) AS coupon_id, c.code AS coupon_code, c.usage_limit, c.per_email_limit, COALESCE(c.used_count, 0) AS used_count, (SELECT GROUP_CONCAT(product_id) FROM discount_products WHERE discount_id = d.id) AS product_ids, (SELECT GROUP_CONCAT(category_id) FROM discount_categories WHERE discount_id = d.id) AS category_ids, (SELECT GROUP_CONCAT(collection_id) FROM discount_collections WHERE discount_id = d.id) AS collection_ids FROM discounts d LEFT JOIN coupons c ON c.discount_id = d.id AND c.is_active = 1 WHERE d.is_active = 1 AND (d.starts_at IS NULL OR d.starts_at <= CURRENT_TIMESTAMP(3)) AND (d.ends_at IS NULL OR d.ends_at > CURRENT_TIMESTAMP(3)) AND (d.method = 'AUTOMATIC' OR (d.method = 'COUPON' AND c.code = ?)) ORDER BY d.priority DESC, d.id`, [input.couponCode ?? ""], connection);
  const couponRows = discounts.filter((discount) => discount.method === "COUPON");
  if (input.couponCode && !couponRows.length) throw new CommerceError("INVALID_COUPON", "The coupon is invalid or expired.");
  if (input.couponCode && couponRows.some((coupon) => coupon.usage_limit !== null && coupon.used_count >= coupon.usage_limit)) throw new CommerceError("COUPON_LIMIT", "The coupon usage limit has been reached.");
  if (input.customerEmail) for (const coupon of couponRows) if (coupon.coupon_id && coupon.per_email_limit !== null) { const count = await selectOne<CountRow>("SELECT COUNT(*) AS redemption_count FROM coupon_redemptions WHERE coupon_id = ? AND customer_email = ?", [coupon.coupon_id, input.customerEmail], connection); if (Number(count?.redemption_count ?? 0) >= coupon.per_email_limit) throw new CommerceError("COUPON_LIMIT", "This email has reached the coupon usage limit."); }
  const pool = input.couponCode ? couponRows : discounts.filter((discount) => discount.method === "AUTOMATIC");
  const candidates = pool.filter((discount) => discount.minimum_subtotal_pence === null || subtotalPence >= discount.minimum_subtotal_pence).map((discount) => { const eligible = lines.filter((line) => lineEligible(line, discount)); const eligibleSubtotal = eligible.reduce((sum, line) => sum + line.subtotalPence, 0); return { discount, eligible, eligibleSubtotal, amount: discountAmount(discount, eligibleSubtotal), freeShipping: discount.discount_type === "FREE_SHIPPING" && eligibleSubtotal > 0 }; });
  const selected = candidates.sort((a, b) => (Number(b.freeShipping) - Number(a.freeShipping)) || b.amount - a.amount)[0] ?? null;
  if (input.couponCode && (!selected || (!selected.amount && !selected.freeShipping))) throw new CommerceError("INVALID_COUPON", "The coupon does not apply to this cart.");
  if (selected?.amount) { let remaining = selected.amount; selected.eligible.forEach((line, index) => { const amount = index === selected.eligible.length - 1 ? remaining : Math.min(remaining, Math.floor(selected.amount * line.subtotalPence / selected.eligibleSubtotal)); line.discountPence = amount; line.totalPence -= amount; remaining -= amount; }); }
  const shippingRows = await selectRows<ShippingRow>(`SELECT CAST(m.id AS CHAR) AS id, m.name, m.method_type, m.price_pence, m.free_over_pence, m.estimated_days_min, m.estimated_days_max FROM shipping_methods m INNER JOIN shipping_zones z ON z.id = m.zone_id AND z.is_active = 1 INNER JOIN shipping_zone_countries c ON c.zone_id = z.id WHERE c.country_code = ? AND m.is_active = 1 ORDER BY z.sort_order, m.sort_order, m.id`, [input.countryCode], connection);
  if (!shippingRows.length) throw new CommerceError("DELIVERY_UNAVAILABLE", "Delivery is not configured for this country.");
  const chosen = input.shippingMethodId ? shippingRows.find((method) => method.id === input.shippingMethodId) : shippingRows[0];
  if (!chosen) throw new CommerceError("DELIVERY_UNAVAILABLE", "The selected delivery method is unavailable.");
  const discountPence = lines.reduce((sum, line) => sum + line.discountPence, 0);
  const discountedSubtotal = subtotalPence - discountPence;
  const shippingPence = selected?.freeShipping || chosen.method_type === "FREE_SHIPPING" || (chosen.free_over_pence !== null && discountedSubtotal >= chosen.free_over_pence) ? 0 : chosen.price_pence;
  const taxPence = 0;
  return { lines, subtotalPence, discountPence, shippingPence, taxPence, totalPence: discountedSubtotal + shippingPence + taxPence, currency: "GBP", discount: selected ? { id: selected.discount.id, name: selected.discount.name, couponId: selected.discount.coupon_id, couponCode: selected.discount.coupon_code, freeShipping: selected.freeShipping } : null, shippingMethod: { id: chosen.id, name: chosen.name, estimatedDaysMin: chosen.estimated_days_min, estimatedDaysMax: chosen.estimated_days_max }, shippingMethods: shippingRows.map((method) => ({ id: method.id, name: method.name, pricePence: method.price_pence, estimatedDaysMin: method.estimated_days_min, estimatedDaysMax: method.estimated_days_max })) };
}
