import Link from "next/link";
import type { RowDataPacket } from "mysql2/promise";
import PageHeader from "@/components/admin/PageHeader";
import Pagination, { parsePage } from "@/components/admin/Pagination";
import StatusBadge from "@/components/admin/StatusBadge";
import LegacyBadge from "@/components/admin/LegacyBadge";
import { selectRows, selectOne } from "@/lib/db/query";
import { requireAdministrator } from "@/lib/auth/session";
interface Payment extends RowDataPacket { id: string; order_id: string; order_number: string; payment_type: string; status: string; provider: string; provider_reference: string | null; amount_pence: number; currency: string; source: string; created_at: Date }
export default async function PaymentsPage({ searchParams }: { searchParams: Promise<{ q?: string; type?: string; source?: string; page?: string }> }) {
  await requireAdministrator(["OWNER", "MANAGER"]);
  const query = await searchParams, q = query.q?.trim().slice(0, 100) ?? "", type = ["CHARGE", "REFUND"].includes(query.type ?? "") ? query.type! : "ALL", source = ["LIVE", "LEGACY"].includes(query.source ?? "") ? query.source! : "ALL";
  const where = "(o.order_number LIKE ? OR COALESCE(p.provider_reference,'') LIKE ?) AND (?='ALL' OR p.payment_type=?) AND (?='ALL' OR p.source=?)";
  const values = [`%${q}%`, `%${q}%`, type, type, source, source];
  const total = Number((await selectOne<RowDataPacket>(`SELECT COUNT(*) n FROM payments p JOIN orders o ON o.id=p.order_id WHERE ${where}`, values))?.n ?? 0), page = Math.min(parsePage(query.page), Math.max(1, Math.ceil(total / 30)));
  const payments = await selectRows<Payment>(`SELECT p.*,CAST(p.id AS CHAR) id,CAST(p.order_id AS CHAR) order_id,o.order_number FROM payments p JOIN orders o ON o.id=p.order_id WHERE ${where} ORDER BY p.created_at DESC,p.id DESC LIMIT 30 OFFSET ?`, [...values, (page - 1) * 30]);
  return <div><PageHeader eyebrow="Sales" title="Payments & refunds" description="Recorded transactions, refund history and payment references." /><form className="my-5 flex flex-wrap gap-3"><input name="q" aria-label="Order or transaction reference" defaultValue={q} placeholder="Order or transaction reference" className="rounded-lg border border-zinc-300 px-3 py-2 text-sm" /><select name="type" aria-label="Payment type" defaultValue={type} className="rounded-lg border border-zinc-300 px-3 text-sm"><option value="ALL">All transactions</option><option value="CHARGE">Charges</option><option value="REFUND">Refunds</option></select><select name="source" aria-label="Payment origin" defaultValue={source} className="rounded-lg border border-zinc-300 px-3 text-sm"><option value="ALL">All origins</option><option value="LEGACY">Historical</option><option value="LIVE">New website</option></select><button className="rounded-lg bg-zinc-950 px-4 py-2 text-sm text-white">Filter</button></form>
    <div className="overflow-hidden rounded-xl border border-zinc-200 bg-white"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-zinc-50"><tr>{["Order", "Type", "Provider / reference", "Status", "Amount", "Date", "Origin"].map(label => <th key={label} className="px-4 py-3 font-medium">{label}</th>)}</tr></thead><tbody>{payments.map(payment => <tr key={payment.id} className="border-t border-zinc-100"><td className="px-4 py-3"><Link className="text-amber-800 underline" href={`/admin/orders/${payment.order_id}`}>{payment.order_number}</Link></td><td className="px-4 py-3">{payment.payment_type}</td><td className="px-4 py-3">{payment.provider}<p className="mt-1 break-all text-xs text-zinc-500">{payment.provider_reference || "No reference recorded"}</p></td><td className="px-4 py-3"><StatusBadge status={payment.status} /></td><td className="px-4 py-3">{new Intl.NumberFormat("en-GB", { style: "currency", currency: payment.currency }).format(payment.amount_pence / 100)}</td><td className="whitespace-nowrap px-4 py-3">{new Date(payment.created_at).toLocaleDateString("en-GB")}</td><td className="px-4 py-3"><LegacyBadge source={payment.source} /></td></tr>)}</tbody></table></div><Pagination pathname="/admin/payments" page={page} pageSize={30} totalItems={total} query={{ q, type, source }} /></div>
  </div>;
}
