import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Check } from "lucide-react";
import ProductDetailActions from "@/components/commerce/ProductDetailActions";
import { getStorefrontProduct } from "@/lib/commerce/catalog";

export const dynamic = "force-dynamic";
interface ProductPageProps { params: Promise<{ slug: string }> }
export async function generateMetadata({ params }: ProductPageProps): Promise<Metadata> { const product = await getStorefrontProduct((await params).slug); return product ? { title: `${product.name} | N7 Cosmetics`, description: product.shortDescription ?? product.description ?? undefined } : {}; }
function money(pence: number) { return new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP" }).format(pence / 100); }
export default async function ProductPage({ params }: ProductPageProps) { const product = await getStorefrontProduct((await params).slug); if (!product) notFound(); const commerceProduct = { slug: product.slug, name: product.name, image: product.image, pricePence: product.pricePence }; const soldOut = product.trackInventory && product.stockOnHand <= 0; return <div className="min-h-screen bg-[#f3eee5] pb-24 pt-40 text-[#1c1814] sm:pt-48"><div className="mx-auto max-w-7xl px-5 sm:px-8"><Link className="inline-flex items-center gap-2 text-xs uppercase tracking-[0.18em] text-black/50 hover:text-black" href="/yusuf-bhai-originals"><ArrowLeft size={14} />Back to collection</Link><div className="mt-8 grid gap-12 lg:grid-cols-2 lg:items-center"><div><div className="relative aspect-square overflow-hidden bg-[#e8dfd1]"><Image alt={product.imageAlt} className="object-contain p-10 drop-shadow-[0_35px_25px_rgba(0,0,0,0.18)]" fill priority sizes="(max-width: 1024px) 100vw, 50vw" src={product.image} /></div>{product.video ? <video className="mt-4 aspect-video w-full bg-black object-contain" controls preload="metadata" src={product.video} /> : null}</div><div><p className="text-[10px] font-semibold uppercase tracking-[0.28em] text-[#8d6745]">{product.brand ?? "N7 Cosmetics"} / {product.audience.toLowerCase()}</p><h1 className="mt-4 font-heading text-5xl leading-none text-[#1c1814] sm:text-6xl">{product.name}</h1>{product.inspiredBy ? <p className="mt-3 text-sm italic text-black/50">Inspired by {product.inspiredBy}</p> : null}<div className="mt-6 flex items-baseline gap-3"><span className="font-heading text-3xl">{money(product.pricePence)}</span>{product.compareAtPricePence ? <span className="text-lg text-black/35 line-through">{money(product.compareAtPricePence)}</span> : null}</div><p className="mt-6 max-w-xl text-base font-light leading-7 text-black/62">{product.description ?? product.shortDescription ?? "A distinctive fragrance composed for a memorable signature."}</p>{product.notes.length ? <div className="mt-6 flex flex-wrap gap-2">{product.notes.map((note) => <span className="rounded-full border border-black/15 px-3 py-1.5 text-xs" key={note}>{note}</span>)}</div> : null}<ProductDetailActions product={commerceProduct} soldOut={soldOut} /><ul className="mt-8 grid gap-3 border-t border-black/12 pt-6 text-sm text-black/55"><li className="flex items-center gap-2"><Check size={15} />Secure checkout</li><li className="flex items-center gap-2"><Check size={15} />Inventory verified before order placement</li><li className="flex items-center gap-2"><Check size={15} />Delivery calculated at checkout</li></ul></div></div></div></div>; }
