import Notice from "@/components/admin/Notice";
import PageHeader from "@/components/admin/PageHeader";
import PasswordInput from "@/components/admin/PasswordInput";
import { requireAdministrator } from "@/lib/auth/session";
import { updatePasswordAction, updateProfileAction } from "./actions";

const input = "mt-1.5 w-full rounded-lg border border-zinc-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-amber-700 focus:ring-2 focus:ring-amber-100";
export default async function ProfilePage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string; "password-error"?: string }> }) {
  const [admin, query] = await Promise.all([requireAdministrator(), searchParams]);
  return <div><PageHeader eyebrow="Administrator" title="Your profile" description="Update your account details and password." />{query.saved ? <Notice type="success">Profile details updated.</Notice> : null}{query.error === "email" ? <Notice>That email address is already used by another administrator.</Notice> : query.error ? <Notice>Check your name and email.</Notice> : null}{query["password-error"] === "current" ? <Notice>The current password is incorrect.</Notice> : query["password-error"] ? <Notice>Use matching passwords with at least 12 characters, uppercase, lowercase, a number, and a symbol.</Notice> : null}<div className="mt-7 grid gap-6 lg:grid-cols-2"><form action={updateProfileAction} className="h-fit rounded-xl border border-zinc-200 bg-white p-5 shadow-sm"><h2 className="font-body text-base font-semibold">Profile details</h2><div className="mt-5 space-y-5"><label className="block text-sm font-medium text-zinc-700">Name<input className={input} defaultValue={admin.name} maxLength={120} name="name" required /></label><label className="block text-sm font-medium text-zinc-700">Email<input autoComplete="email" className={input} defaultValue={admin.email} maxLength={190} name="email" required type="email" /></label><label className="block text-sm font-medium text-zinc-700">Role<input className={`${input} bg-zinc-100 text-zinc-500`} disabled value={admin.role} /></label></div><button className="mt-5 rounded-lg bg-zinc-950 px-4 py-2.5 text-sm font-semibold text-white" type="submit">Save profile</button></form><form action={updatePasswordAction} className="rounded-xl border border-zinc-200 bg-white p-5 shadow-sm"><h2 className="font-body text-base font-semibold">Change password</h2><p className="mt-1 text-sm text-zinc-500">Changing your password signs out all active admin sessions.</p><div className="mt-5 space-y-5"><PasswordInput autoComplete="current-password" label="Current password" maxLength={128} name="currentPassword" required /><PasswordInput autoComplete="new-password" hint="At least 12 characters with uppercase, lowercase, a number, and a symbol." label="New password" maxLength={128} minLength={12} name="password" required /><PasswordInput autoComplete="new-password" label="Confirm new password" maxLength={128} minLength={12} name="passwordConfirmation" required /></div><button className="mt-5 rounded-lg bg-zinc-950 px-4 py-2.5 text-sm font-semibold text-white" type="submit">Change password</button></form></div></div>;
}
