"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { formCheckbox, formString, isDatabaseId, nullableFormString, poundsToPence } from "@/lib/admin/form";
import { writeAuditLog } from "@/lib/auth/audit";
import { getRequestMetadata } from "@/lib/auth/request";
import { requireAdministrator } from "@/lib/auth/session";
import { executeMutation } from "@/lib/db/query";
import { withTransaction } from "@/lib/db/transaction";

const zoneSchema = z.object({ name: z.string().min(2).max(150), countries: z.array(z.string().regex(/^[A-Z]{2}$/)).min(1).max(250), isActive: z.boolean(), sortOrder: z.number().int().min(-100000).max(100000) });
const methodSchema = z.object({ zoneId: z.string().regex(/^[1-9]\d*$/), name: z.string().min(2).max(150), methodType: z.enum(["FLAT_RATE", "FREE_SHIPPING", "LOCAL_PICKUP"]), pricePence: z.number().int().nonnegative(), freeOverPence: z.number().int().nonnegative().nullable(), estimatedDaysMin: z.number().int().nonnegative().nullable(), estimatedDaysMax: z.number().int().nonnegative().nullable(), isActive: z.boolean(), sortOrder: z.number().int().min(-100000).max(100000) }).refine((item) => item.estimatedDaysMin === null || item.estimatedDaysMax === null || item.estimatedDaysMax >= item.estimatedDaysMin);
function optionalNumber(value: string | null) { return value ? Number(value) : null; }
function parseZone(formData: FormData) { const countries = formString(formData, "countries").split(",").map((code) => code.trim().toUpperCase()).filter(Boolean); return zoneSchema.safeParse({ name: formString(formData, "name"), countries: [...new Set(countries)], isActive: formCheckbox(formData, "isActive"), sortOrder: Number(formString(formData, "sortOrder")) }); }
function parseMethod(formData: FormData) { const price = poundsToPence(formString(formData, "price")); const freeRaw = nullableFormString(formData, "freeOver"); return methodSchema.safeParse({ zoneId: formString(formData, "zoneId"), name: formString(formData, "name"), methodType: formString(formData, "methodType"), pricePence: price, freeOverPence: freeRaw ? poundsToPence(freeRaw) : null, estimatedDaysMin: optionalNumber(nullableFormString(formData, "estimatedDaysMin")), estimatedDaysMax: optionalNumber(nullableFormString(formData, "estimatedDaysMax")), isActive: formCheckbox(formData, "isActive"), sortOrder: Number(formString(formData, "sortOrder")) }); }
async function audit(entityType: string, id: string, action: string, summary: string) { const [admin, metadata] = await Promise.all([requireAdministrator(["OWNER", "MANAGER"]), getRequestMetadata()]); await writeAuditLog({ administratorId: admin.id, action, entityType, entityId: id, summary, ipAddress: metadata.ipAddress }); }
async function syncCountries(zoneId: string, countries: string[], connection: Parameters<typeof executeMutation>[2]) { await executeMutation("DELETE FROM shipping_zone_countries WHERE zone_id = ?", [zoneId], connection); for (const country of countries) await executeMutation("INSERT INTO shipping_zone_countries (zone_id, country_code) VALUES (?, ?)", [zoneId, country], connection); }
export async function createZoneAction(formData: FormData): Promise<void> { await requireAdministrator(["OWNER", "MANAGER"]); const parsed = parseZone(formData); if (!parsed.success) redirect("/admin/delivery?error=zone"); const zone = parsed.data; const id = await withTransaction(async (connection) => { const result = await executeMutation("INSERT INTO shipping_zones (name, is_active, sort_order) VALUES (?, ?, ?)", [zone.name, zone.isActive, zone.sortOrder], connection); const id = String(result.insertId); await syncCountries(id, zone.countries, connection); return id; }); await audit("shipping_zone", id, "SHIPPING_ZONE_CREATE", `Created shipping zone ${zone.name}`); revalidatePath("/admin/delivery"); redirect("/admin/delivery?saved=1"); }
export async function updateZoneAction(id: string, formData: FormData): Promise<void> { await requireAdministrator(["OWNER", "MANAGER"]); if (!isDatabaseId(id)) return; const parsed = parseZone(formData); if (!parsed.success) redirect("/admin/delivery?error=zone"); const zone = parsed.data; await withTransaction(async (connection) => { await executeMutation("UPDATE shipping_zones SET name = ?, is_active = ?, sort_order = ? WHERE id = ?", [zone.name, zone.isActive, zone.sortOrder, id], connection); await syncCountries(id, zone.countries, connection); }); await audit("shipping_zone", id, "SHIPPING_ZONE_UPDATE", `Updated shipping zone ${zone.name}`); revalidatePath("/admin/delivery"); redirect("/admin/delivery?saved=1"); }
export async function createMethodAction(formData: FormData): Promise<void> { await requireAdministrator(["OWNER", "MANAGER"]); const parsed = parseMethod(formData); if (!parsed.success) redirect("/admin/delivery?error=method"); const method = parsed.data; const result = await executeMutation(`INSERT INTO shipping_methods (zone_id, name, method_type, price_pence, free_over_pence, estimated_days_min, estimated_days_max, is_active, sort_order) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`, [method.zoneId, method.name, method.methodType, method.pricePence, method.freeOverPence, method.estimatedDaysMin, method.estimatedDaysMax, method.isActive, method.sortOrder]); await audit("shipping_method", String(result.insertId), "SHIPPING_METHOD_CREATE", `Created shipping method ${method.name}`); revalidatePath("/admin/delivery"); redirect("/admin/delivery?saved=1"); }
export async function updateMethodAction(id: string, formData: FormData): Promise<void> { await requireAdministrator(["OWNER", "MANAGER"]); if (!isDatabaseId(id)) return; const parsed = parseMethod(formData); if (!parsed.success) redirect("/admin/delivery?error=method"); const method = parsed.data; await executeMutation(`UPDATE shipping_methods SET zone_id = ?, name = ?, method_type = ?, price_pence = ?, free_over_pence = ?, estimated_days_min = ?, estimated_days_max = ?, is_active = ?, sort_order = ? WHERE id = ?`, [method.zoneId, method.name, method.methodType, method.pricePence, method.freeOverPence, method.estimatedDaysMin, method.estimatedDaysMax, method.isActive, method.sortOrder, id]); await audit("shipping_method", id, "SHIPPING_METHOD_UPDATE", `Updated shipping method ${method.name}`); revalidatePath("/admin/delivery"); redirect("/admin/delivery?saved=1"); }
