import "./load-env";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { readFile, readdir } from "node:fs/promises";
import mysql, { type RowDataPacket } from "mysql2/promise";
import { getDatabaseConfig } from "../lib/env";
import { executeMutation, selectOne, selectRows } from "../lib/db/query";
import { withTransaction } from "../lib/db/transaction";
import { encryptSecret, decryptSecret } from "../lib/security/encryption";
import { defaultMetaSettings, getMetaSettings, type MetaSettings } from "../lib/meta/settings";
import { consentGranted } from "../lib/meta/consent";
import { saveConsent } from "../lib/meta/consent";
import { browserMetaPurchase, readMetaCheckoutContext, queueMetaPurchase } from "../lib/meta/orders";
import { makeMetaEvent, queueMetaEvent, resolveEventData, type MetaServerEvent } from "../lib/meta/events";
import { processMetaQueue } from "../lib/meta/queue";
import { getMetaOrderDelivery, recordMetaWorkerHealth, syncMetaDeliveryDiagnostics } from "../lib/meta/diagnostics";
import { readMetaCheckoutCapture } from "../lib/meta/orders";
import { visitorMetaUserData } from "../lib/meta/visitor";
import { hashMetaValue, metaExternalId } from "../lib/meta/identity";
import { metaAdvancedMatching } from "../lib/meta/matching";
import { saveMetaMatchingProfile } from "../lib/meta/matching-profile";
import { createOrder } from "../lib/commerce/orders";
import { getMetaDeliveryHealth } from "../lib/meta/delivery-health";
import { applyPaymentIntent, type PaymentIntentSnapshot } from "../lib/payments/stripe";
import type { CheckoutInput } from "../lib/commerce/validation";

async function run() {
  const config = getDatabaseConfig();
  assert.ok(["127.0.0.1", "localhost", "::1"].includes(config.host), "Checks require a local database");
  const database = `n7_meta_test_${Date.now()}`;
  assert.match(database, /^n7_meta_test_\d+$/);
  const options = { host: config.host, port: config.port, user: process.env.DB_ROOT_PASSWORD ? "root" : config.user, password: process.env.DB_ROOT_PASSWORD || config.password };
  const setup = await mysql.createConnection({ ...options, multipleStatements: true });
  const originalFetch = globalThis.fetch;
  const sent: { url: string; body: { data: MetaServerEvent[]; test_event_code?: string } }[] = [];
  let responseStatus = 200;
  let checks = 0;
  let created = false;
  const check = (value: unknown, message: string) => { assert.ok(value, message); checks++; };
  try {
    await setup.query(`CREATE DATABASE \`${database}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`); created = true;
    await setup.changeUser({ database });
    for (const name of (await readdir("database/migrations")).filter(name => name.endsWith(".sql")).sort()) await setup.query(await readFile(`database/migrations/${name}`, "utf8"));
    globalThis.n7MySqlPool = mysql.createPool({ ...options, database, connectionLimit: 6, supportBigNumbers: true, bigNumberStrings: true, timezone: "Z" });
    globalThis.fetch = async (url, init) => {
      assert.ok(String(url).startsWith("https://graph.facebook.com/v26.0/"));
      assert.equal(String(url).includes("access_token"), false);
      assert.equal(new Headers(init?.headers).get("authorization"), "Bearer fake-meta-token");
      sent.push({ url: String(url), body: JSON.parse(String(init?.body)) });
      return Response.json(responseStatus === 200 ? { events_received: 1 } : { error: { code: responseStatus === 503 ? 2 : 190, message: "Must never persist private@example.com or fake-meta-token", is_transient: responseStatus === 503 } }, { status: responseStatus });
    };
    const settings: MetaSettings = { ...defaultMetaSettings, pixelId: "123456789", capiTokenEncrypted: encryptSecret("fake-meta-token") };
    const save = async (s: MetaSettings) => executeMutation("UPDATE site_settings SET value_json = ? WHERE setting_key = 'meta.configuration'", [JSON.stringify(s)]);
    await save(settings);
    check(!(await getMetaSettings()).capiTokenEncrypted.includes("fake-meta-token"), "Token must be encrypted at rest");
    const consent = await saveConsent(new Request("https://n7.test"), true);
    const request = new Request("https://n7.test/api/commerce/orders", { headers: { cookie: `n7_marketing_consent=${consent}; _fbp=fb.1.1700000000000.123456`, "user-agent": "Integration test", "x-forwarded-for": "203.0.113.1" } });
    check(await consentGranted(consent), "Saved consent is granted");
    check(await readMetaCheckoutContext(new Request("https://n7.test")) === undefined, "No consent means no checkout attribution");
    const optedOut = new Request(request, { headers: { cookie: `n7_marketing_consent=${consent}; n7_marketing_optout=1` } });
    check(await readMetaCheckoutContext(optedOut) === undefined, "An immediate local opt-out overrides a stale server consent record");
    check((await readMetaCheckoutCapture(optedOut)).reason === "CONSENT_DENIED", "Declined tracking has an explicit diagnostic reason");
    check((await readMetaCheckoutCapture(new Request("https://n7.test"))).reason === "NO_CONSENT", "Missing consent is distinguished from a tracking error");
    const context = await readMetaCheckoutContext(request);
    assert.ok(context);
    const anonymous = await visitorMetaUserData(request, consent);
    check(!anonymous.em && !anonymous.ph && anonymous.external_id?.[0] === metaExternalId(consent), "Anonymous consenting events share the visitor ID without invented contact data");
    const matchingConsent = await saveConsent(new Request("https://n7.test"), true);
    const matchingRequest = new Request("https://n7.test/api/meta/matching", { headers: { cookie: `n7_marketing_consent=${matchingConsent}` } });
    const matchingInput = { email: "NewBuyer@Example.test", phone: "07123 456789", fullName: "New Buyer", city: "London", region: "Greater London", postalCode: "SW1A 1AA", countryCode: "GB" as const };
    const beforeOrder = await saveMetaMatchingProfile(matchingRequest, matchingInput);
    check(beforeOrder?.matching.em === hashMetaValue("newbuyer@example.test") && beforeOrder.matching.ph === hashMetaValue("447123456789") && beforeOrder.externalId === metaExternalId(matchingConsent), "Available checkout details supply canonical Pixel matching before order creation");
    check((await visitorMetaUserData(matchingRequest, matchingConsent)).em?.[0] === beforeOrder?.matching.em, "Subsequent CAPI browsing events can reuse the same pre-order contact hashes");
    const matchingStored = await selectOne<RowDataPacket>("SELECT matching_data_encrypted FROM meta_consents WHERE id = ?", [matchingConsent]);
    const storedMatching = decryptSecret(matchingStored!.matching_data_encrypted);
    check(!storedMatching.includes("NewBuyer") && !storedMatching.includes("07123") && Object.values(JSON.parse(storedMatching)).every(value => Array.isArray(value) && value.length === 1 && /^[a-f0-9]{64}$/.test(value[0])), "The pre-order profile is encrypted and contains only normalized hashes");
    check(Number((await selectOne<RowDataPacket>("SELECT COUNT(*) AS count FROM meta_event_jobs"))?.count) === 0, "Saving matching never creates fabricated events or conversions");
    check(!await saveMetaMatchingProfile(new Request("https://n7.test"), matchingInput), "Anonymous requests cannot create matching profiles");
    check(!await saveMetaMatchingProfile(new Request(matchingRequest, { headers: { cookie: `n7_marketing_consent=${matchingConsent}; n7_marketing_optout=1` } }), matchingInput), "An immediate local opt-out blocks pre-order matching");
    await saveMetaMatchingProfile(matchingRequest, { ...matchingInput, region: undefined });
    check((await visitorMetaUserData(matchingRequest, matchingConsent)).st?.[0] === beforeOrder?.matching.st, "An unchanged pre-order buyer and locality retain their known optional county");
    await saveMetaMatchingProfile(matchingRequest, { email: "otherbuyer@example.test" });
    const changedMatching = await visitorMetaUserData(matchingRequest, matchingConsent);
    check(changedMatching.em?.[0] === hashMetaValue("otherbuyer@example.test") && !changedMatching.ph && !changedMatching.st, "A different buyer cannot inherit the previous person's contact or address hashes");
    await save({ ...settings, capiEnabled: false, capiTokenEncrypted: "" });
    check(Boolean(await saveMetaMatchingProfile(matchingRequest, matchingInput)), "Pixel-only matching works without a Conversions API token");
    await save({ ...settings, pixelEnabled: false });
    const serverMatching = await saveMetaMatchingProfile(matchingRequest, matchingInput);
    check(serverMatching?.pixelId === "" && serverMatching.matching.em === beforeOrder?.matching.em, "CAPI-only matching is supported without enabling a browser Pixel");
    await save({ ...settings, pixelEnabled: false, capiEnabled: false });
    check(!await saveMetaMatchingProfile(matchingRequest, matchingInput), "Disabled tracking does not collect contact matching");
    await save(settings);
    await executeMutation("UPDATE meta_consents SET expires_at = DATE_SUB(CURRENT_TIMESTAMP(3), INTERVAL 1 SECOND) WHERE id = ?", [matchingConsent]);
    check(!await saveMetaMatchingProfile(matchingRequest, matchingInput), "Expired consent cannot be renewed by a contact update");
    await saveConsent(matchingRequest, true);
    await Promise.all([saveMetaMatchingProfile(matchingRequest, matchingInput), saveConsent(matchingRequest, false)]);
    check(!await saveMetaMatchingProfile(matchingRequest, matchingInput) && (await selectOne<RowDataPacket>("SELECT matching_data_encrypted FROM meta_consents WHERE id = ?", [matchingConsent]))?.matching_data_encrypted === null, "Concurrent withdrawal erases pre-order matching and blocks later updates");
    const product = await executeMutation("INSERT INTO products (name, slug, status, track_inventory) VALUES ('Meta test', 'meta-test', 'ACTIVE', 1)");
    const variant = await executeMutation("INSERT INTO product_variants (product_id, title, sku, price_pence, stock_on_hand, is_default) VALUES (?, '100 ml', 'META-TEST', 4500, 50, 1)", [product.insertId]);
    const zone = await executeMutation("INSERT INTO shipping_zones (name) VALUES ('UK test')");
    await executeMutation("INSERT INTO shipping_zone_countries (zone_id, country_code) VALUES (?, 'GB')", [zone.insertId]);
    const delivery = await executeMutation("INSERT INTO shipping_methods (name, method_type, price_pence) VALUES ('Delivery', 'DELIVERY', 299)");
    await executeMutation("INSERT INTO shipping_method_rates (method_id,zone_id,price_pence) VALUES (?,?,299)", [delivery.insertId, zone.insertId]);
    const address = { fullName: "Meta Test", line1: "1 Test Street", city: "London", region: "Greater London", postalCode: "SW1A 1AA", countryCode: "GB" as const, phone: "02079460000" };
    const input: CheckoutInput = { idempotencyKey: randomUUID(), expectedTotalPence: 4799, items: [{ slug: "meta-test", quantity: 1 }], customer: { name: address.fullName, email: "private@example.com", phone: address.phone }, countryCode: "GB", billingAddress: address, shippingAddress: address, paymentMethod: "STRIPE", shippingMethodId: String(delivery.insertId) };
    const paidIntent = (orderId: string, live = true): PaymentIntentSnapshot => ({ id: `pi_fixture_${orderId}`, amount: 4799, amount_received: 4799, currency: "gbp", livemode: live, status: "succeeded", metadata: { n7_order_id: orderId } });
    const order = await createOrder(input, "live", undefined, context);
    const stored = await selectOne<RowDataPacket>("SELECT payload_encrypted FROM meta_order_contexts WHERE order_id = ?", [order.id]);
    check(stored && !decryptSecret(stored.payload_encrypted).includes("private@example.com"), "Stored matching data contains hashes, not email addresses");
    const purchaseUser = JSON.parse(decryptSecret(stored!.payload_encrypted)).userData;
    check(["em", "ph", "fn", "ln", "ct", "st", "zp", "country", "external_id"].every(key => /^[a-f0-9]{64}$/.test(purchaseUser[key]?.[0])), "Purchase contains all available normalized hashed matching fields");
    check(purchaseUser.fn[0] === hashMetaValue("meta") && purchaseUser.zp[0] === hashMetaValue("sw1a1aa") && !JSON.stringify(purchaseUser).includes(address.line1), "Matching uses billing names and locality without street addresses");
    const recognized = await visitorMetaUserData(request, consent);
    check(recognized.em?.[0] === purchaseUser.em[0] && recognized.ph?.[0] === purchaseUser.ph[0] && recognized.external_id?.[0] === anonymous.external_id?.[0], "Known consenting views reuse checkout hashes and the original visitor ID");
    check(recognized.st?.[0] === hashMetaValue("greaterlondon") && metaAdvancedMatching(recognized).st === recognized.st[0], "Known ViewContent and Pixel matching share the same hashed county");
    const repeatAddress = { ...address, region: "" };
    const repeat = await createOrder({ ...input, idempotencyKey: randomUUID(), billingAddress: repeatAddress, shippingAddress: repeatAddress }, "live", undefined, context);
    const repeatedContext = await selectOne<RowDataPacket>("SELECT payload_encrypted FROM meta_order_contexts WHERE order_id = ?", [repeat.id]);
    check(JSON.parse(decryptSecret(repeatedContext!.payload_encrypted)).userData.st?.[0] === purchaseUser.st[0] && (await visitorMetaUserData(request, consent)).st?.[0] === purchaseUser.st[0], "A same-person, same-locality checkout with omitted optional county preserves known county for Purchase and later views");
    const otherVisitor = await saveConsent(new Request("https://n7.test"), true);
    check(!(await visitorMetaUserData(request, otherVisitor)).em, "Matching profiles do not leak across consenting browsers");
    await executeMutation("UPDATE meta_consents SET matching_data_encrypted = ?, expires_at = DATE_SUB(CURRENT_TIMESTAMP(3), INTERVAL 1 SECOND) WHERE id = ?", [encryptSecret(JSON.stringify({ em: purchaseUser.em })), otherVisitor]);
    const expiredRequest = new Request("https://n7.test", { headers: { cookie: `n7_marketing_consent=${otherVisitor}` } });
    check(Object.keys(await visitorMetaUserData(expiredRequest, otherVisitor)).length === 0, "Expired consent cannot disclose known matching fields");
    await saveConsent(expiredRequest, true);
    check(!(await visitorMetaUserData(expiredRequest, otherVisitor)).em, "Renewing an expired choice does not revive a stale matching profile");
    await processMetaQueue(); check(sent.length === 0, "An unpaid order is never a purchase event");
    await applyPaymentIntent(paidIntent(order.id));
    await Promise.all([processMetaQueue(), processMetaQueue()]);
    check(sent.length === 1, "Concurrent workers send a paid order once");
    check(sent[0].body.data[0].event_id === `n7_purchase_${order.id}`, "Purchase event ID is stable");
    check(!sent[0].body.data[0].event_source_url.includes("?"), "Receipt tokens are absent from source URLs");
    check(JSON.stringify(sent[0].body.data[0].custom_data).includes(`n7_variant_${variant.insertId}`), "Purchase uses the same catalogue variant ID");
    const browser = await browserMetaPurchase(order.id, request);
    check(browser?.eventId === sent[0].body.data[0].event_id && browser.data.value === 47.99, "Browser and server purchase share ID and paid total including delivery");
    check(browser?.externalId === anonymous.external_id?.[0] && browser?.externalId === sent[0].body.data[0].user_data.external_id?.[0], "Browser views, checkout and both Purchase copies share the canonical External ID");
    check(browser?.matching?.st === purchaseUser.st[0] && sent[0].body.data[0].user_data.st?.[0] === browser?.matching?.st, "Browser and server Purchase carry the same county hash without raw address details");
    check(!await browserMetaPurchase(order.id, new Request("https://n7.test")), "A shared receipt is not permission to track another browser");
    await applyPaymentIntent(paidIntent(order.id)); await processMetaQueue(); check(sent.length === 1, "Webhook replays cannot create duplicate conversions");
    check((await selectOne<RowDataPacket>("SELECT payload_encrypted FROM meta_event_jobs WHERE event_name = 'Purchase'"))?.payload_encrypted === null, "Accepted payloads are removed");
    const coverage = await selectOne<RowDataPacket>("SELECT matching_fields_json FROM meta_event_jobs WHERE event_name = 'Purchase'");
    const flags = typeof coverage!.matching_fields_json === "string" ? JSON.parse(coverage!.matching_fields_json) : coverage!.matching_fields_json;
    check(flags.em && flags.fn && flags.ln && flags.country && flags.external_id && Object.values(flags).every(value => typeof value === "boolean"), "Accepted events retain only matching-presence flags after payload erasure");
    const delivered = await getMetaOrderDelivery(order.id);
    check(delivered?.status === "Sent" && delivered.attempts === 1 && delivered.sentAt && delivered.lastAttemptAt, "Order diagnostics show Meta acceptance, attempts and timestamps");
    await recordMetaWorkerHealth(true);
    check(Boolean((await selectOne<RowDataPacket>("SELECT last_success_at FROM meta_worker_health WHERE id = 1"))?.last_success_at), "Worker success produces an observable heartbeat");
    const historicId = randomUUID();
    await executeMutation(`INSERT INTO meta_event_jobs (pixel_id,event_id,event_name,status,event_time,last_attempt_at,last_error)
      VALUES (?,?,'PageView','FAILED',DATE_SUB(CURRENT_TIMESTAMP(3),INTERVAL 3 DAY),DATE_SUB(CURRENT_TIMESTAMP(3),INTERVAL 3 DAY),'Unable to read the encrypted event. Check the application encryption key.')`, [settings.pixelId, historicId]);
    const historicHealth = await getMetaDeliveryHealth();
    check(historicHealth.worker.state === "running" && historicHealth.credentialError === null && historicHealth.history.some(issue => issue.name === "PageView") && !historicHealth.activeIssues.some(issue => issue.message.includes("encrypted")), "An old failed PageView is retained as history without falsely reporting a current encryption outage");
    const originalCiphertext = settings.capiTokenEncrypted;
    await save({ ...settings, capiTokenEncrypted: "v1.invalid.invalid.invalid" });
    check(Boolean((await getMetaDeliveryHealth()).credentialError), "An actually unreadable current token remains a prominent credential error");
    await save({ ...settings, capiTokenEncrypted: originalCiphertext });
    check(!JSON.stringify(await getMetaDeliveryHealth()).includes("fake-meta-token"), "Delivery health never contains credentials or encrypted token values");
    await executeMutation("UPDATE meta_event_jobs SET last_attempt_at=CURRENT_TIMESTAMP(3) WHERE event_id=?", [historicId]);
    const recentHealth = await getMetaDeliveryHealth();
    check(recentHealth.activeIssues.some(issue => issue.status === "FAILED") && !recentHealth.history.some(issue => issue.message.includes("encrypted")), "A recent terminal failure is still prominently reported instead of hidden in history");
    await executeMutation("UPDATE meta_event_jobs SET last_attempt_at=DATE_SUB(CURRENT_TIMESTAMP(3),INTERVAL 3 DAY) WHERE event_id=?", [historicId]);
    const noConsent = await createOrder({ ...input, idempotencyKey: randomUUID() }, "live", undefined, undefined, "NO_CONSENT");
    await applyPaymentIntent(paidIntent(noConsent.id));
    check((await getMetaOrderDelivery(noConsent.id))?.reason === "Marketing consent was not granted at checkout.", "Paid untracked orders retain their actual skip reason");
    const view = await resolveEventData({ name: "ViewContent", eventId: randomUUID(), path: "/products/meta-test", items: [{ slug: "meta-test", quantity: 1 }] });
    check(view.content_ids?.[0] === browser?.data.content_ids?.[0] && view.value === 45, "View and purchase catalogue IDs match");
    await assert.rejects(resolveEventData({ name: "AddToCart", eventId: randomUUID(), path: "/", items: [{ slug: "not-found", quantity: 1 }] })); checks++;
    const retryId = randomUUID();
    const event = makeMetaEvent("AddToCart", retryId, "/products/meta-test?email=secret", { client_user_agent: "Test" }, view);
    await queueMetaEvent(event, settings, consent);
    const queued = await selectOne<RowDataPacket>("SELECT payload_encrypted, matching_fields_json FROM meta_event_jobs WHERE event_id = ?", [retryId]);
    check(JSON.parse(decryptSecret(queued!.payload_encrypted)).user_data.external_id[0] === metaExternalId(consent), "The queue fills missing External IDs using the same consent identity as Pixel");
    const viewId = randomUUID();
    await queueMetaEvent(makeMetaEvent("ViewContent", viewId, "/products/meta-test", { ...recognized, external_id: [metaExternalId("incorrect-caller")] }, view), settings, consent);
    const queuedView = await selectOne<RowDataPacket>("SELECT payload_encrypted FROM meta_event_jobs WHERE event_id = ?", [viewId]);
    const viewUser = JSON.parse(decryptSecret(queuedView!.payload_encrypted)).user_data;
    check(viewUser.external_id[0] === browser?.externalId && viewUser.em[0] === recognized.em?.[0] && viewUser.ph[0] === recognized.ph?.[0] && viewUser.st[0] === browser?.matching?.st, "ViewContent gets the canonical External ID while preserving known email, phone and county hashes");
    responseStatus = 503; await processMetaQueue();
    let retry = await selectOne<RowDataPacket>("SELECT * FROM meta_event_jobs WHERE event_id = ?", [retryId]);
    check(retry?.status === "PENDING" && retry?.attempts === 1, "Transient failures back off");
    check(!String(retry?.last_error).includes("private@example.com") && !String(retry?.last_error).includes("fake-meta-token"), "Remote error text cannot leak identifiers or credentials");
    await executeMutation("UPDATE meta_event_jobs SET next_attempt_at = CURRENT_TIMESTAMP(3) WHERE event_id IN (?, ?)", [retryId, viewId]);
    responseStatus = 200; await processMetaQueue();
    retry = await selectOne<RowDataPacket>("SELECT * FROM meta_event_jobs WHERE event_id = ?", [retryId]);
    const retried = sent.filter(item => item.body.data[0].event_id === retryId);
    check(retry?.status === "SENT" && retried.length === 2 && retried.every(item => item.body.data[0].event_time === event.event_time), "Retry preserves the event ID and actual event time");
    check((await selectOne<RowDataPacket>("SELECT status FROM meta_event_jobs WHERE event_id = ?", [viewId]))?.status === "SENT" && sent.filter(item => item.body.data[0].event_id === retryId || item.body.data[0].event_id === viewId).every(item => item.body.data[0].user_data.external_id?.[0] === browser?.externalId), "Retries preserve External ID matching for cart and content events");
    const testOrder = await createOrder({ ...input, idempotencyKey: randomUUID() }, "test", undefined, context);
    await applyPaymentIntent(paidIntent(testOrder.id, false));
    const before = sent.length; await processMetaQueue();
    check(sent.length === before && !await browserMetaPurchase(testOrder.id, request), "Stripe test payments never enter live reporting");
    const testSettings = { ...settings, testEventCode: "TEST123" };
    await save(testSettings);
    const testContext = await readMetaCheckoutContext(request); assert.ok(testContext);
    const testPurchase = await createOrder({ ...input, idempotencyKey: randomUUID() }, "test", undefined, testContext);
    await applyPaymentIntent(paidIntent(testPurchase.id, false)); await processMetaQueue();
    check(sent.at(-1)?.body.test_event_code === "TEST123" && !await browserMetaPurchase(testPurchase.id, request), "Test payments use CAPI Test Events only");
    check((await getMetaOrderDelivery(testPurchase.id))?.testMode, "Accepted test purchases stay visibly marked as test events");
    await save(settings);
    const pixelOnlyConsent = await saveConsent(new Request("https://n7.test"), true);
    const pixelOnlySettings = { ...settings, capiEnabled: false };
    await save(pixelOnlySettings);
    const pixelRequest = new Request("https://n7.test", { headers: { cookie: `n7_marketing_consent=${pixelOnlyConsent}` } });
    const pixelContext = await readMetaCheckoutContext(pixelRequest);
    assert.ok(pixelContext);
    const pixelOrder = await createOrder({ ...input, idempotencyKey: randomUUID() }, "live", undefined, pixelContext);
    await applyPaymentIntent(paidIntent(pixelOrder.id));
    const beforePixelOnly = sent.length;
    await processMetaQueue();
    check(sent.length === beforePixelOnly, "Pixel-only configuration never queues or sends a server Purchase");
    check(metaAdvancedMatching(await visitorMetaUserData(pixelRequest, pixelOnlyConsent)).st === hashMetaValue("greaterlondon"), "Pixel-only configuration retains valid consenting county matching without requiring CAPI");
    check((await browserMetaPurchase(pixelOrder.id, pixelRequest))?.matching?.st === hashMetaValue("greaterlondon"), "Pixel-only Purchase receives the same verified county matching");
    await save(settings);
    const otherAddress = { ...address, region: "", city: "Bristol", postalCode: "BS1 1AA" };
    await createOrder({ ...input, idempotencyKey: randomUUID(), billingAddress: otherAddress, shippingAddress: otherAddress }, "live", undefined, context);
    check(!(await visitorMetaUserData(request, consent)).st, "Changed checkout locality drops the previous county instead of inventing one");
    const revokedId = randomUUID();
    await queueMetaEvent(makeMetaEvent("PageView", revokedId, "/", { client_user_agent: "Test" }, {}), settings, consent);
    await saveConsent(request, false);
    check(!await consentGranted(consent), "Withdrawal persists");
    check((await selectOne<RowDataPacket>("SELECT matching_data_encrypted FROM meta_consents WHERE id = ?", [consent]))?.matching_data_encrypted === null, "Withdrawal erases the recognized visitor matching profile");
    check(Object.keys(await visitorMetaUserData(request, consent)).length === 0, "Withdrawn visitors receive no server matching data");
    check((await selectOne<RowDataPacket>("SELECT status, payload_encrypted FROM meta_event_jobs WHERE event_id = ?", [revokedId]))?.status === "CANCELLED", "Withdrawal cancels pending events");
    check((await selectRows("SELECT order_id FROM meta_order_contexts WHERE consent_id = ?", [consent])).length === 0, "Withdrawal removes pending order attribution");
    check(!await browserMetaPurchase(order.id, request), "Receipt cannot track after withdrawal");
    await syncMetaDeliveryDiagnostics();
    check((await getMetaOrderDelivery(order.id))?.status === "Sent", "Consent withdrawal does not erase the safe historical acceptance record");
    await withTransaction(connection => queueMetaPurchase(order.id, connection));
    const expiryId = randomUUID();
    await queueMetaEvent(makeMetaEvent("PageView", expiryId, "/", { client_user_agent: "Test" }, {}), settings, null);
    await executeMutation("UPDATE meta_event_jobs SET event_time = DATE_SUB(CURRENT_TIMESTAMP(3), INTERVAL 48 HOUR) WHERE event_id = ?", [expiryId]);
    await processMetaQueue();
    check((await selectOne<RowDataPacket>("SELECT status, payload_encrypted FROM meta_event_jobs WHERE event_id = ?", [expiryId]))?.payload_encrypted === null, "Expired events are erased instead of being sent beyond deduplication window");
    await saveConsent(request, true);
    await executeMutation("RENAME TABLE meta_order_contexts TO meta_order_contexts_unavailable");
    try {
      const untrackedOrder = await createOrder({ ...input, idempotencyKey: randomUUID() }, "live", undefined, context);
      check(Boolean(await selectOne("SELECT id FROM orders WHERE id = ?", [untrackedOrder.id])), "Tracking storage failure cannot roll back a valid order");
      check((await selectOne<RowDataPacket>("SELECT capture_reason FROM meta_order_diagnostics WHERE order_id = ?", [untrackedOrder.id]))?.capture_reason === "CAPTURE_FAILED", "Context storage failures are recorded without failing checkout");
    } finally {
      await executeMutation("RENAME TABLE meta_order_contexts_unavailable TO meta_order_contexts");
    }
    await executeMutation("RENAME TABLE meta_order_diagnostics TO meta_order_diagnostics_unavailable");
    try {
      const unobserved = await createOrder({ ...input, idempotencyKey: randomUUID() }, "live", undefined, context);
      check(Boolean(await selectOne("SELECT id FROM orders WHERE id = ?", [unobserved.id])), "Diagnostic storage failure cannot roll back checkout");
      check(Boolean(await selectOne("SELECT order_id FROM meta_order_contexts WHERE order_id = ?", [unobserved.id])), "Diagnostic storage failure preserves eligible tracking context");
    } finally { await executeMutation("RENAME TABLE meta_order_diagnostics_unavailable TO meta_order_diagnostics"); }
    await executeMutation("UPDATE meta_event_jobs SET created_at = DATE_SUB(CURRENT_TIMESTAMP(3), INTERVAL 31 DAY) WHERE event_id = ?", [`n7_purchase_${order.id}`]);
    await processMetaQueue();
    check((await getMetaOrderDelivery(order.id))?.status === "Sent", "Order acceptance remains visible after queue metadata expires");
    console.log(`${checks} Meta integration checks passed; no real Meta or Stripe calls, charges or emails.`);
  } finally {
    globalThis.fetch = originalFetch;
    await globalThis.n7MySqlPool?.end(); globalThis.n7MySqlPool = undefined;
    if (created) await setup.query(`DROP DATABASE \`${database}\``);
    await setup.end();
  }
}
void run().catch(error => { console.error(error instanceof Error ? error.message : "Meta integration checks failed"); process.exitCode = 1; });
