import "./load-env";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import mysql from "mysql2/promise";
import type { RowDataPacket } from "mysql2/promise";
import nodemailer from "nodemailer";
import { getDatabaseConfig } from "../lib/env";
import { executeMutation, selectOne, selectRows } from "../lib/db/query";
import { encryptSecret, decryptSecret } from "../lib/security/encryption";
import { enqueueEmail, processEmailQueue, retryQueuedEmail } from "../lib/email/queue";
import { confirmNewsletter, subscribeNewsletter, unsubscribeNewsletter } from "../lib/email/newsletter";
import { verifySmtpConnection } from "../lib/email/service";
import { createOrder } from "../lib/commerce/orders";
import { applyPaymentIntent, type PaymentIntentSnapshot } from "../lib/payments/stripe";
import type { CheckoutInput } from "../lib/commerce/validation";
import { emailPreviews } from "../lib/email/previews";
import { checkoutMarketingNotice } from "../lib/commerce/checkout-preferences";

async function run(): Promise<void> {
  const config = getDatabaseConfig();
  if (!["localhost", "127.0.0.1", "::1"].includes(config.host)) throw new Error("Email integration checks require a local database server.");
  const database = `n7_email_test_${Date.now()}`;
  assert.match(database, /^n7_email_test_[0-9]+$/);
  const options = { host: config.host, port: config.port, user: process.env.DB_ROOT_PASSWORD ? "root" : config.user, password: process.env.DB_ROOT_PASSWORD || config.password, ssl: config.ssl ? {} : undefined, multipleStatements: true };
  const setup = await mysql.createConnection(options);
  const originalTransport = nodemailer.createTransport;
  let created = false;
  let sends = 0;
  let fail = false;
  let checks = 0;
  const check = (value: unknown, description: string) => { assert.ok(value, description); checks++; };
  const job = (id: string) => selectOne<RowDataPacket>("SELECT * FROM email_jobs WHERE id = ?", [id]);
  nodemailer.createTransport = (() => ({ verify: async () => true, close() {}, sendMail: async () => { sends++; if (fail) throw new Error("Mock temporary SMTP failure"); await new Promise((resolve) => setTimeout(resolve, 10)); return { accepted: ["test@example.com"], messageId: "mock-only" }; } })) as unknown as typeof nodemailer.createTransport;
  try {
    await setup.query(`CREATE DATABASE \`${database}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`);
    created = true;
    await setup.changeUser({ database });
    const migrations = (await readdir("database/migrations")).filter((file) => file.endsWith(".sql")).sort();
    for (const migration of migrations) await setup.query(await readFile(path.join("database/migrations", migration), "utf8"));
    globalThis.n7MySqlPool = mysql.createPool({ ...options, multipleStatements: false, database, connectionLimit: 5, supportBigNumbers: true, bigNumberStrings: true });
    const message = { to: "test@example.com", subject: "N7 integration check", text: "Mock delivery only", html: "<p>Mock delivery only</p>", templateKey: "integration-check" };
    const id = await enqueueEmail(message, { dedupeKey: "dedupe-check" });
    const duplicate = await enqueueEmail(message, { dedupeKey: "dedupe-check" });
    check(id === duplicate, "Duplicate enqueue must return the existing job");
    check(!(await job(id))?.payload_encrypted.includes(message.text), "Queued content must be encrypted");
    check(await processEmailQueue() === 0 && sends === 0, "Missing SMTP must not attempt delivery");
    check((await job(id))?.attempts === 0, "Missing SMTP must not consume attempts");
    check((await verifySmtpConnection()).status === "SKIPPED", "Incomplete settings must be reported");
    const settings: Record<string, unknown> = { "smtp.host": "smtp.invalid", "smtp.port": 465, "smtp.secure": true, "smtp.user": "test@example.com", "smtp.password_encrypted": encryptSecret("mock-password"), "smtp.from_email": "test@example.com", "smtp.from_name": "N7 Cosmetics", "contact.email": "team@example.com" };
    for (const [key, value] of Object.entries(settings)) await executeMutation("INSERT INTO site_settings (setting_key, setting_group, value_json, is_public) VALUES (?, ?, ?, 0) ON DUPLICATE KEY UPDATE value_json = VALUES(value_json)", [key, key.split(".")[0], JSON.stringify(value)]);
    check((await verifySmtpConnection()).status === "SENT" && sends === 0, "Verification must not send a message");
    fail = true;
    await processEmailQueue();
    check((await job(id))?.status === "PENDING" && (await job(id))?.attempts === 1, "Failed send must remain retryable");
    check(await processEmailQueue() === 0, "Retry delay must be respected");
    fail = false;
    await executeMutation("UPDATE email_jobs SET available_at = CURRENT_TIMESTAMP(3) WHERE id = ?", [id]);
    await processEmailQueue();
    check((await job(id))?.status === "SENT" && (await job(id))?.attempts === 2, "Retry must recover a failed delivery");
    const attempts = await selectRows<RowDataPacket>("SELECT status FROM email_logs WHERE email_job_id = ? ORDER BY id", [id]);
    check(attempts.map((row) => row.status).join(",") === "FAILED,SENT", "Attempt history must survive successful retry");
    const failing = await enqueueEmail(message, { dedupeKey: "exhaustion-check" });
    fail = true;
    for (let attempt = 0; attempt < 5; attempt++) { await executeMutation("UPDATE email_jobs SET available_at = CURRENT_TIMESTAMP(3) WHERE id = ?", [failing]); await processEmailQueue(); }
    check((await job(failing))?.status === "FAILED" && (await job(failing))?.attempts === 5, "Five failures must stop automatic retries");
    fail = false;
    const concurrent = await enqueueEmail(message, { dedupeKey: "concurrent-check" });
    const before = sends;
    await Promise.all([processEmailQueue(1), processEmailQueue(1)]);
    check(sends === before + 1 && (await job(concurrent))?.status === "SENT", "Concurrent workers must claim a job once");
    const stale = await enqueueEmail(message, { dedupeKey: "stale-claim" });
    await executeMutation("UPDATE email_jobs SET status = 'PROCESSING', lock_token = ?, locked_at = DATE_SUB(CURRENT_TIMESTAMP(3), INTERVAL 6 MINUTE) WHERE id = ?", [randomUUID(), stale]);
    await processEmailQueue();
    check((await job(stale))?.status === "SENT", "Worker must recover a stale claim");
    const expired = await enqueueEmail({ ...message, templateKey: "admin-password-reset" }, { dedupeKey: "expired-reset", expiresAt: new Date(Date.now() - 60_000) });
    const reset = await enqueueEmail({ ...message, templateKey: "admin-password-reset" }, { dedupeKey: "valid-reset", expiresAt: new Date(Date.now() + 60_000) });
    await processEmailQueue();
    check((await job(expired))?.status === "CANCELLED" && (await job(expired))?.payload_encrypted === null, "Expired reset must be cancelled and scrubbed");
    check((await job(reset))?.status === "SENT" && (await job(reset))?.payload_encrypted === null, "Sent reset content must be scrubbed");
    check(!await retryQueuedEmail(reset, true), "Scrubbed reset must not be resent");
    const restrictedReset = await enqueueEmail({ ...message, templateKey: "admin-password-reset" }, { dedupeKey: "restricted-reset", expiresAt: new Date(Date.now() + 60_000) });
    check(!await retryQueuedEmail(restrictedReset, false), "Managers must not retry administrator reset emails");
    check(await retryQueuedEmail(id, false), "Delivered order-style email can be explicitly resent");
    const resend = await selectOne<RowDataPacket>("SELECT id FROM email_jobs WHERE dedupe_key LIKE ?", [`resend:${id}:%`]);
    check(resend && String(resend.id) !== id && (await job(id))?.status === "SENT", "Explicit resend gets a new job and preserves the original history");
    await processEmailQueue();

    check(await subscribeNewsletter("subscriber@example.com", "127.0.0.2") === "accepted", "Newsletter signup must be saved");
    const newsletter = await selectOne<RowDataPacket>("SELECT * FROM newsletter_subscribers WHERE email = 'subscriber@example.com'");
    check(newsletter?.status === "PENDING", "Signup must not activate without confirmation");
    const confirmation = await selectOne<RowDataPacket>("SELECT * FROM email_jobs WHERE subscriber_id = ? AND template_key = 'newsletter-confirmation'", [newsletter!.id]);
    const confirmationContent = JSON.parse(decryptSecret(confirmation!.payload_encrypted)) as { text: string };
    const token = confirmationContent.text.match(/token=([A-Za-z0-9_-]{43})/)![1];
    check(await confirmNewsletter(token), "Valid token must confirm subscription");
    check(!await confirmNewsletter(token), "Confirmation token must be single use");
    const welcome = await selectOne<RowDataPacket>("SELECT * FROM email_jobs WHERE subscriber_id = ? AND template_key = 'newsletter-welcome'", [newsletter!.id]);
    const welcomeContent = JSON.parse(decryptSecret(welcome!.payload_encrypted)) as { unsubscribeUrl: string };
    const unsubscribeToken = new URL(welcomeContent.unsubscribeUrl).searchParams.get("token")!;
    check(await unsubscribeNewsletter(unsubscribeToken), "Valid unsubscribe must succeed");
    check(await unsubscribeNewsletter(unsubscribeToken), "Repeated unsubscribe must remain successful");
    check((await job(String(welcome!.id)))?.status === "CANCELLED", "Unsubscribe must cancel pending welcome email");
    check(!await unsubscribeNewsletter("invalid"), "Invalid token must not change subscribers");
    for (let attempt = 0; attempt < 4; attempt++) await subscribeNewsletter("rate@example.com", "127.0.0.3");
    await subscribeNewsletter("rate@example.com", "127.0.0.3");
    check(await subscribeNewsletter("rate@example.com", "127.0.0.3") === "limited", "Newsletter requests must be rate limited");

    await executeMutation("INSERT INTO products (name, slug, status) VALUES ('Test fragrance', 'email-test-fragrance', 'ACTIVE')");
    const product = await selectOne<RowDataPacket>("SELECT id FROM products WHERE slug = 'email-test-fragrance'");
    await executeMutation("INSERT INTO product_variants (product_id, title, sku, price_pence, stock_on_hand, is_default) VALUES (?, '100 ml', 'EMAIL-TEST', 5000, 10, 1)", [product!.id]);
    const zone = await executeMutation("INSERT INTO shipping_zones (name) VALUES ('Email test delivery')");
    await executeMutation("INSERT INTO shipping_zone_countries (zone_id, country_code) VALUES (?, 'GB')", [zone.insertId]);
    const delivery = await executeMutation("INSERT INTO shipping_methods (name, method_type, price_pence) VALUES ('Standard delivery', 'DELIVERY', 500)");
    await executeMutation("INSERT INTO shipping_method_rates (method_id,zone_id,price_pence) VALUES (?,?,500)", [delivery.insertId, zone.insertId]);
    const address = { fullName: "Email Test", line1: "12 Test Street", city: "London", postalCode: "SW1A 1AA", countryCode: "GB" as const, phone: "02079460000" };
    const input: CheckoutInput = { idempotencyKey: randomUUID(), expectedTotalPence: 5500, items: [{ slug: "email-test-fragrance", quantity: 1 }], customer: { name: "Email Test", email: "customer@example.com", phone: address.phone }, countryCode: "GB", billingAddress: address, shippingAddress: address, paymentMethod: "STRIPE", marketingOptOut: false };
    const order = await createOrder(input, "test");
    const repeated = await createOrder(input, "test");
    check(order.order_number === repeated.order_number, "Checkout retry must reuse the order");
    const preference = await selectOne<RowDataPacket>("SELECT marketing_opt_out, marketing_notice, marketing_preference_recorded_at FROM orders WHERE id = ?", [order.id]);
    check(preference?.marketing_opt_out === 0 && preference.marketing_notice === checkoutMarketingNotice && preference.marketing_preference_recorded_at, "Checkout must save the choice, exact notice and timestamp");
    const softSubscriber = await selectOne<RowDataPacket>("SELECT * FROM newsletter_subscribers WHERE email = ?", [input.customer.email]);
    check(softSubscriber?.status === "ACTIVE" && softSubscriber.marketing_basis === "SOFT_OPT_IN" && softSubscriber.confirmed_at === null, "Checkout soft opt-in must not be recorded as explicit consent");
    const softWelcomes = await selectRows<RowDataPacket>("SELECT * FROM email_jobs WHERE subscriber_id = ?", [softSubscriber!.id]);
    check(softWelcomes.length === 1, "Retrying a checkout must not duplicate marketing welcome emails");
    const softContent = JSON.parse(decryptSecret(softWelcomes[0].payload_encrypted)) as { unsubscribeUrl: string };
    const softUnsubscribeToken = new URL(softContent.unsubscribeUrl).searchParams.get("token")!;
    const intent = (id: string, orderId: string): PaymentIntentSnapshot => ({ id, amount: 5500, amount_received: 5500, currency: "gbp", livemode: false, status: "succeeded", metadata: { n7_order_id: orderId } });
    check((await selectRows("SELECT id FROM email_jobs WHERE template_key = 'order-confirmation'")).length === 0, "Unpaid checkout must not send confirmation");
    await applyPaymentIntent(intent("pi_email_test", order.id), { id: "evt_email_test", type: "payment_intent.succeeded" });
    await applyPaymentIntent(intent("pi_email_test", order.id), { id: "evt_email_test", type: "payment_intent.succeeded" });
    const orderJobs = await selectRows<RowDataPacket>("SELECT recipient, template_key FROM email_jobs WHERE template_key IN ('order-confirmation','new-order-team')");
    check(orderJobs.length === 2, "Checkout retry must not duplicate customer or team emails");
    check(orderJobs.some((row) => row.recipient === input.customer.email) && orderJobs.some((row) => row.recipient === "team@example.com"), "Order messages must use the saved customer and store recipients");
    await createOrder({ ...input, idempotencyKey: randomUUID(), marketingOptOut: true }, "test");
    check((await selectOne<RowDataPacket>("SELECT status FROM newsletter_subscribers WHERE id = ?", [softSubscriber!.id]))?.status === "UNSUBSCRIBED", "Checkout opt-out must unsubscribe an existing active customer");
    check((await job(String(softWelcomes[0].id)))?.status === "CANCELLED", "Checkout opt-out must cancel queued marketing");
    const confirmationJob = await selectOne<RowDataPacket>("SELECT status FROM email_jobs WHERE recipient = ? AND template_key = 'order-confirmation'", [input.customer.email]);
    check(confirmationJob?.status === "PENDING", "Marketing opt-out must leave order confirmations queued");
    check(await unsubscribeNewsletter(softUnsubscribeToken), "Checkout subscribers must have a working, repeatable unsubscribe link");
    await createOrder({ ...input, idempotencyKey: randomUUID() }, "test");
    check((await selectOne<RowDataPacket>("SELECT status FROM newsletter_subscribers WHERE id = ?", [softSubscriber!.id]))?.status === "UNSUBSCRIBED", "An unchecked box on a later checkout must respect the previous unsubscribe");
    await createOrder({ ...input, idempotencyKey: randomUUID(), customer: { ...input.customer, email: "new-optout@example.com" }, marketingOptOut: true }, "test");
    const newOptOut = await selectOne<RowDataPacket>("SELECT * FROM newsletter_subscribers WHERE email = 'new-optout@example.com'");
    check(newOptOut?.status === "UNSUBSCRIBED" && newOptOut.marketing_basis === null, "A new checkout opt-out must create a suppression record without marketing consent");
    check((await selectRows("SELECT id FROM email_jobs WHERE subscriber_id = ?", [newOptOut!.id])).length === 0, "An opted-out new customer must receive no subscription email");
    await createOrder({ ...input, idempotencyKey: randomUUID(), customer: { ...input.customer, email: "rate@example.com" } }, "test");
    check((await selectOne<RowDataPacket>("SELECT status FROM newsletter_subscribers WHERE email = 'rate@example.com'"))?.status === "PENDING", "Checkout must not bypass a pending newsletter confirmation");
    const withoutNotice = await createOrder({ ...input, idempotencyKey: randomUUID(), customer: { ...input.customer, email: "cart-wallet@example.com" }, marketingOptOut: undefined }, "test");
    check(!await selectOne("SELECT id FROM newsletter_subscribers WHERE email = 'cart-wallet@example.com'"), "Express checkout without a displayed notice must not subscribe the customer");
    check((await selectOne<RowDataPacket>("SELECT marketing_opt_out, marketing_preference_recorded_at FROM orders WHERE id = ?", [withoutNotice.id]))?.marketing_preference_recorded_at === null, "Missing preference must not be treated as an unchecked opt-out");
    const second = await createOrder({ ...input, idempotencyKey: randomUUID() }, "test");
    await setup.query("CREATE TRIGGER fail_test_email BEFORE INSERT ON email_jobs FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Mock outbox failure'");
    await assert.rejects(applyPaymentIntent(intent("pi_email_second", second.id), { id: "evt_email_second", type: "payment_intent.succeeded" })); checks++;
    const pending = await selectOne<RowDataPacket>("SELECT payment_status FROM orders WHERE id = ?", [second.id]);
    check(pending?.payment_status === "PENDING", "Payment update rolls back with its email outbox so the webhook can retry");

    const directory = path.resolve("reports/email-previews");
    await mkdir(directory, { recursive: true });
    for (const preview of emailPreviews({ appUrl: "https://n7.eluvaire.com", contactEmail: "preview@example.com" })) await writeFile(path.join(directory, `${preview.key}.html`), preview.email.html);
    console.log(`${checks} integration checks passed using mocked SMTP. Preview HTML: ${directory}`);
  } finally {
    nodemailer.createTransport = originalTransport;
    await globalThis.n7MySqlPool?.end();
    globalThis.n7MySqlPool = undefined;
    if (created) { await setup.query(`DROP DATABASE \`${database}\``); console.log("Temporary email test database removed."); }
    await setup.end();
  }
}
run().catch((error) => { console.error(error instanceof Error ? error.message : "Email integration check failed."); process.exitCode = 1; });
