import "./load-env";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import mysql from "mysql2/promise";
import type { RowDataPacket } from "mysql2/promise";
import nodemailer from "nodemailer";
import { getDatabaseConfig } from "../lib/env";
import { executeMutation, selectOne, selectRows } from "../lib/db/query";
import { encryptSecret, decryptSecret } from "../lib/security/encryption";
import { enqueueEmail, processEmailQueue, retryQueuedEmail } from "../lib/email/queue";
import { confirmNewsletter, subscribeNewsletter, unsubscribeNewsletter } from "../lib/email/newsletter";
import { getSmtpSettings, verifySmtpConnection } from "../lib/email/service";
import { saveVerifiedSmtpSettings } from "../lib/email/configuration";
import { readSmtpValues, saveEmailSetting, settingsRevision } from "../lib/email/store";
import { legacyNotificationSettings, notificationRecipients, smtpSchema } from "../lib/email/settings";
import { getEmailPreferences } from "../lib/email/brand";
import { enqueueStoreNotification } from "../lib/email/notifications";
import { enqueueOrderEmails } from "../lib/email/orders";
import { enqueueLowStockAlerts } from "../lib/email/alerts";
import { withTransaction } from "../lib/db/transaction";
import { createOrder } from "../lib/commerce/orders";
import { applyPaymentIntent, type PaymentIntentSnapshot } from "../lib/payments/stripe";
import type { CheckoutInput } from "../lib/commerce/validation";
import { emailPreviews } from "../lib/email/previews";
import { checkoutMarketingNotice } from "../lib/commerce/checkout-preferences";
import { saveEmailCopySettings } from "../lib/email/copy-store";
import { smtpTestEmail } from "../lib/email/templates";

async function run(): Promise<void> {
  const config = getDatabaseConfig();
  if (!["localhost", "127.0.0.1", "::1"].includes(config.host)) throw new Error("Email integration checks require a local database server.");
  const database = `n7_email_test_${Date.now()}`;
  assert.match(database, /^n7_email_test_[0-9]+$/);
  const options = { host: config.host, port: config.port, user: process.env.DB_ROOT_PASSWORD ? "root" : config.user, password: process.env.DB_ROOT_PASSWORD || config.password, ssl: config.ssl ? {} : undefined, multipleStatements: true };
  const setup = await mysql.createConnection(options);
  const originalTransport = nodemailer.createTransport;
  let created = false;
  let sends = 0;
  let fail = false;
  let failRecipient = "";
  const delivered: Array<{ to: string; messageId: string; replyTo?: string; from: { address: string } }> = [];
  let checks = 0;
  const check = (value: unknown, description: string) => { assert.ok(value, description); checks++; };
  const job = (id: string) => selectOne<RowDataPacket>("SELECT * FROM email_jobs WHERE id = ?", [id]);
  nodemailer.createTransport = (() => ({ verify: async () => true, close() {}, sendMail: async (email: typeof delivered[number]) => { sends++; delivered.push(email); if (fail || email.to === failRecipient) throw new Error("Mock temporary SMTP failure"); await new Promise((resolve) => setTimeout(resolve, 10)); return { accepted: [email.to], messageId: email.messageId || "mock-only" }; } })) as unknown as typeof nodemailer.createTransport;
  try {
    await setup.query(`CREATE DATABASE \`${database}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`);
    created = true;
    await setup.changeUser({ database });
    const migrations = (await readdir("database/migrations")).filter((file) => file.endsWith(".sql")).sort();
    for (const migration of migrations) await setup.query(await readFile(path.join("database/migrations", migration), "utf8"));
    globalThis.n7MySqlPool = mysql.createPool({ ...options, multipleStatements: false, database, connectionLimit: 5, supportBigNumbers: true, bigNumberStrings: true });
    const defaultCopyRevision = settingsRevision({});
    const customCopy = { intro: ["Delivery check for ", ". This is our saved email wording."] };
    const copySaved = await saveEmailCopySettings("smtp-test", customCopy, defaultCopyRevision, null);
    check(copySaved.success, "Email wording must save using the existing settings table");
    const copyPreferences = await getEmailPreferences();
    check(JSON.stringify(copyPreferences.emailCopy?.["smtp-test"]) === JSON.stringify(customCopy), "Saved email wording must load for outgoing messages");
    const customMessage = smtpTestEmail(copyPreferences, "live-recipient@example.com");
    check(customMessage.text.includes("Delivery check for live-recipient@example.com") && customMessage.html.includes("Delivery check for live-recipient@example.com"), "Both versions must use saved wording and the actual recipient");
    const copyJob = await enqueueEmail({ ...customMessage, to: "live-recipient@example.com", templateKey: "template-copy-check" }, { dedupeKey: "template-copy-check" });
    await executeMutation("UPDATE email_jobs SET status = 'CANCELLED' WHERE id = ?", [copyJob]);
    check(!(await saveEmailCopySettings("smtp-test", { recipient: ["overridden@example.com"] }, copySaved.success ? copySaved.revision : "", null)).success, "Saving dynamic values through a forged request must fail");
    check(!(await saveEmailCopySettings("smtp-test", { intro: ["Removed the locked recipient"] }, copySaved.success ? copySaved.revision : "", null)).success, "Removing a locked dynamic slot must fail");
    check(!(await saveEmailCopySettings("smtp-test", { title: ["Stale replacement"] }, defaultCopyRevision, null)).success, "Stale edits must not overwrite saved wording");
    const copyRace = await Promise.all([
      saveEmailCopySettings("contact-receipt", { title: ["First edit"] }, defaultCopyRevision, null),
      saveEmailCopySettings("contact-receipt", { title: ["Second edit"] }, defaultCopyRevision, null),
    ]);
    check(copyRace.filter((result) => result.success).length === 1, "Concurrent first saves must have exactly one winner");
    const raceWinner = copyRace.find((result) => result.success)!;
    check(raceWinner.success && (await saveEmailCopySettings("contact-receipt", {}, raceWinner.revision, null)).success, "An edited template can be reset to defaults");
    check(copySaved.success && (await saveEmailCopySettings("smtp-test", {}, copySaved.revision, null)).success, "Restoring default email wording must persist");
    check(!(await getEmailPreferences()).emailCopy?.["smtp-test"]?.intro, "Default restore removes the override from outgoing messages");
    const queuedCopy = JSON.parse(decryptSecret((await job(copyJob))!.payload_encrypted)) as { text: string };
    check(queuedCopy.text === customMessage.text, "Template changes must preserve already queued message snapshots");
    const copyAudit = await selectOne<RowDataPacket & { count: number }>("SELECT COUNT(*) AS count FROM audit_logs WHERE action = 'EMAIL_TEMPLATE_UPDATE'");
    check(Number(copyAudit?.count) === 4, "Successful wording changes must be audited without recording rejected edits");
    const message = { to: "test@example.com", subject: "N7 integration check", text: "Mock delivery only", html: "<p>Mock delivery only</p>", templateKey: "integration-check" };
    const id = await enqueueEmail(message, { dedupeKey: "dedupe-check" });
    const duplicate = await enqueueEmail(message, { dedupeKey: "dedupe-check" });
    check(id === duplicate, "Duplicate enqueue must return the existing job");
    check(!(await job(id))?.payload_encrypted.includes(message.text), "Queued content must be encrypted");
    check(await processEmailQueue() === 0 && sends === 0, "Missing SMTP must not attempt delivery");
    check((await job(id))?.attempts === 0, "Missing SMTP must not consume attempts");
    check((await verifySmtpConnection()).status === "SKIPPED", "Incomplete settings must be reported");
    const settings: Record<string, unknown> = { "smtp.host": "smtp.invalid", "smtp.port": 465, "smtp.secure": true, "smtp.user": "test@example.com", "smtp.password_encrypted": encryptSecret("mock-password"), "smtp.from_email": "test@example.com", "smtp.from_name": "N7 Cosmetics", "contact.email": "team@example.com" };
    for (const [key, value] of Object.entries(settings)) await executeMutation("INSERT INTO site_settings (setting_key, setting_group, value_json, is_public) VALUES (?, ?, ?, 0) ON DUPLICATE KEY UPDATE value_json = VALUES(value_json)", [key, key.split(".")[0], JSON.stringify(value)]);
    check((await verifySmtpConnection()).status === "SENT" && sends === 0, "Verification must not send a message");
    const originalRevision = settingsRevision(await readSmtpValues());
    const customSettings = smtpSchema.parse({ provider: "hosted", host: "mail.example.com", port: 587, security: "starttls", user: "smtp-account", password: "  mailbox password  ", fromName: "Store", fromEmail: "store@example.com" });
    check(Boolean((await saveVerifiedSmtpSettings({ ...customSettings, password: "" }, originalRevision, null)).error), "Switching providers requires fresh credentials");
    check(Boolean((await saveVerifiedSmtpSettings(customSettings, originalRevision, null, async () => ({ status: "FAILED", error: "Mock bad credentials" }))).error), "A rejected replacement connection must not activate");
    check(settingsRevision(await readSmtpValues()) === originalRevision, "Failed verification must leave active settings intact");
    check(!(await saveVerifiedSmtpSettings(customSettings, originalRevision, null)).error, "A verified hosted mailbox can replace the old provider");
    const hosted = await getSmtpSettings();
    check(hosted?.host === "mail.example.com" && hosted.password === "  mailbox password  " && !hosted.secure, "Custom SMTP settings and exact password must round-trip through encryption");
    const hostedRevision = settingsRevision(await readSmtpValues());
    check(!(await saveVerifiedSmtpSettings({ ...customSettings, password: "" }, hostedRevision, null)).error, "The same account can keep its saved password");
    check(Boolean((await saveVerifiedSmtpSettings(customSettings, originalRevision, null)).error), "Stale settings forms must not overwrite a newer connection");
    const raceRevision = settingsRevision(await readSmtpValues());
    const raced = await saveVerifiedSmtpSettings(customSettings, raceRevision, null, async () => {
      await saveEmailSetting("smtp.from_name", "Another administrator's update", null);
      return { status: "SENT" };
    });
    check(Boolean(raced.error) && (await getSmtpSettings())?.fromName === "Another administrator's update", "A concurrent update during verification must not be overwritten");
    fail = true;
    await processEmailQueue();
    check((await job(id))?.status === "PENDING" && (await job(id))?.attempts === 1, "Failed send must remain retryable");
    check(await processEmailQueue() === 0, "Retry delay must be respected");
    fail = false;
    const firstMessageId = delivered.at(-1)?.messageId;
    await saveEmailSetting("smtp.from_email", "sender@another.example.com", null);
    await executeMutation("UPDATE email_jobs SET available_at = CURRENT_TIMESTAMP(3) WHERE id = ?", [id]);
    await processEmailQueue();
    check(delivered.at(-1)?.messageId === firstMessageId, "Retries keep the same Message-ID after changing sender domain");
    check((await job(id))?.status === "SENT" && (await job(id))?.attempts === 2, "Retry must recover a failed delivery");
    const attempts = await selectRows<RowDataPacket>("SELECT status FROM email_logs WHERE email_job_id = ? ORDER BY id", [id]);
    check(attempts.map((row) => row.status).join(",") === "FAILED,SENT", "Attempt history must survive successful retry");
    const failing = await enqueueEmail(message, { dedupeKey: "exhaustion-check" });
    fail = true;
    for (let attempt = 0; attempt < 5; attempt++) { await executeMutation("UPDATE email_jobs SET available_at = CURRENT_TIMESTAMP(3) WHERE id = ?", [failing]); await processEmailQueue(); }
    check((await job(failing))?.status === "FAILED" && (await job(failing))?.attempts === 5, "Five failures must stop automatic retries");
    fail = false;
    const concurrent = await enqueueEmail(message, { dedupeKey: "concurrent-check" });
    const before = sends;
    await Promise.all([processEmailQueue(1), processEmailQueue(1)]);
    check(sends === before + 1 && (await job(concurrent))?.status === "SENT", "Concurrent workers must claim a job once");
    const stale = await enqueueEmail(message, { dedupeKey: "stale-claim" });
    await executeMutation("UPDATE email_jobs SET status = 'PROCESSING', lock_token = ?, locked_at = DATE_SUB(CURRENT_TIMESTAMP(3), INTERVAL 6 MINUTE) WHERE id = ?", [randomUUID(), stale]);
    await processEmailQueue();
    check((await job(stale))?.status === "SENT", "Worker must recover a stale claim");
    const expired = await enqueueEmail({ ...message, templateKey: "admin-password-reset" }, { dedupeKey: "expired-reset", expiresAt: new Date(Date.now() - 60_000) });
    const reset = await enqueueEmail({ ...message, templateKey: "admin-password-reset" }, { dedupeKey: "valid-reset", expiresAt: new Date(Date.now() + 60_000) });
    await processEmailQueue();
    check((await job(expired))?.status === "CANCELLED" && (await job(expired))?.payload_encrypted === null, "Expired reset must be cancelled and scrubbed");
    check((await job(reset))?.status === "SENT" && (await job(reset))?.payload_encrypted === null, "Sent reset content must be scrubbed");
    check(!await retryQueuedEmail(reset, true), "Scrubbed reset must not be resent");
    const restrictedReset = await enqueueEmail({ ...message, templateKey: "admin-password-reset" }, { dedupeKey: "restricted-reset", expiresAt: new Date(Date.now() + 60_000) });
    check(!await retryQueuedEmail(restrictedReset, false), "Managers must not retry administrator reset emails");
    check(await retryQueuedEmail(id, false), "Delivered order-style email can be explicitly resent");
    const resend = await selectOne<RowDataPacket>("SELECT id FROM email_jobs WHERE dedupe_key LIKE ?", [`resend:${id}:%`]);
    check(resend && String(resend.id) !== id && (await job(id))?.status === "SENT", "Explicit resend gets a new job and preserves the original history");
    await processEmailQueue();

    check(await subscribeNewsletter("subscriber@example.com", "127.0.0.2") === "accepted", "Newsletter signup must be saved");
    const newsletter = await selectOne<RowDataPacket>("SELECT * FROM newsletter_subscribers WHERE email = 'subscriber@example.com'");
    check(newsletter?.status === "PENDING", "Signup must not activate without confirmation");
    const confirmation = await selectOne<RowDataPacket>("SELECT * FROM email_jobs WHERE subscriber_id = ? AND template_key = 'newsletter-confirmation'", [newsletter!.id]);
    const confirmationContent = JSON.parse(decryptSecret(confirmation!.payload_encrypted)) as { text: string };
    const token = confirmationContent.text.match(/token=([A-Za-z0-9_-]{43})/)![1];
    check(await confirmNewsletter(token), "Valid token must confirm subscription");
    check(!await confirmNewsletter(token), "Confirmation token must be single use");
    const welcome = await selectOne<RowDataPacket>("SELECT * FROM email_jobs WHERE subscriber_id = ? AND template_key = 'newsletter-welcome'", [newsletter!.id]);
    const welcomeContent = JSON.parse(decryptSecret(welcome!.payload_encrypted)) as { unsubscribeUrl: string };
    const unsubscribeToken = new URL(welcomeContent.unsubscribeUrl).searchParams.get("token")!;
    check(await unsubscribeNewsletter(unsubscribeToken), "Valid unsubscribe must succeed");
    check(await unsubscribeNewsletter(unsubscribeToken), "Repeated unsubscribe must remain successful");
    check((await job(String(welcome!.id)))?.status === "CANCELLED", "Unsubscribe must cancel pending welcome email");
    check(!await unsubscribeNewsletter("invalid"), "Invalid token must not change subscribers");
    for (let attempt = 0; attempt < 4; attempt++) await subscribeNewsletter("rate@example.com", "127.0.0.3");
    await subscribeNewsletter("rate@example.com", "127.0.0.3");
    check(await subscribeNewsletter("rate@example.com", "127.0.0.3") === "limited", "Newsletter requests must be rate limited");

    await executeMutation("INSERT INTO products (name, slug, status) VALUES ('Test fragrance', 'email-test-fragrance', 'ACTIVE')");
    const product = await selectOne<RowDataPacket>("SELECT id FROM products WHERE slug = 'email-test-fragrance'");
    await executeMutation("INSERT INTO product_variants (product_id, title, sku, price_pence, stock_on_hand, is_default) VALUES (?, '100 ml', 'EMAIL-TEST', 5000, 10, 1)", [product!.id]);
    const zone = await executeMutation("INSERT INTO shipping_zones (name) VALUES ('Email test delivery')");
    await executeMutation("INSERT INTO shipping_zone_countries (zone_id, country_code) VALUES (?, 'GB')", [zone.insertId]);
    const delivery = await executeMutation("INSERT INTO shipping_methods (name, method_type, price_pence) VALUES ('Standard delivery', 'DELIVERY', 500)");
    await executeMutation("INSERT INTO shipping_method_rates (method_id,zone_id,price_pence) VALUES (?,?,500)", [delivery.insertId, zone.insertId]);
    const address = { fullName: "Email Test", line1: "12 Test Street", city: "London", postalCode: "SW1A 1AA", countryCode: "GB" as const, phone: "02079460000" };
    const input: CheckoutInput = { idempotencyKey: randomUUID(), expectedTotalPence: 5500, items: [{ slug: "email-test-fragrance", quantity: 1 }], customer: { name: "Email Test", email: "customer@example.com", phone: address.phone }, countryCode: "GB", billingAddress: address, shippingAddress: address, paymentMethod: "STRIPE", marketingOptOut: false };
    const order = await createOrder(input, "test");
    check(order.order_number === "N7-1001", "New order numbering starts at N7-1001");
    const repeated = await createOrder(input, "test");
    check(order.order_number === repeated.order_number, "Checkout retry must reuse the order");
    const preference = await selectOne<RowDataPacket>("SELECT marketing_opt_out, marketing_notice, marketing_preference_recorded_at FROM orders WHERE id = ?", [order.id]);
    check(preference?.marketing_opt_out === 0 && preference.marketing_notice === checkoutMarketingNotice && preference.marketing_preference_recorded_at, "Checkout must save the choice, exact notice and timestamp");
    const softSubscriber = await selectOne<RowDataPacket>("SELECT * FROM newsletter_subscribers WHERE email = ?", [input.customer.email]);
    check(softSubscriber?.status === "ACTIVE" && softSubscriber.marketing_basis === "SOFT_OPT_IN" && softSubscriber.confirmed_at === null, "Checkout soft opt-in must not be recorded as explicit consent");
    const softWelcomes = await selectRows<RowDataPacket>("SELECT * FROM email_jobs WHERE subscriber_id = ?", [softSubscriber!.id]);
    check(softWelcomes.length === 1, "Retrying a checkout must not duplicate marketing welcome emails");
    const softContent = JSON.parse(decryptSecret(softWelcomes[0].payload_encrypted)) as { unsubscribeUrl: string };
    const softUnsubscribeToken = new URL(softContent.unsubscribeUrl).searchParams.get("token")!;
    const intent = (id: string, orderId: string): PaymentIntentSnapshot => ({ id, amount: 5500, amount_received: 5500, currency: "gbp", livemode: false, status: "succeeded", metadata: { n7_order_id: orderId } });
    check((await selectRows("SELECT id FROM email_jobs WHERE template_key = 'order-confirmation'")).length === 0, "Unpaid checkout must not send confirmation");
    await applyPaymentIntent(intent("pi_email_test", order.id), { id: "evt_email_test", type: "payment_intent.succeeded" });
    await applyPaymentIntent(intent("pi_email_test", order.id), { id: "evt_email_test", type: "payment_intent.succeeded" });
    const orderJobs = await selectRows<RowDataPacket>("SELECT recipient, template_key FROM email_jobs WHERE template_key IN ('order-confirmation','new-order-team')");
    check(orderJobs.length === 2, "Checkout retry must not duplicate customer or team emails");
    check(orderJobs.some((row) => row.recipient === input.customer.email) && orderJobs.some((row) => row.recipient === "team@example.com"), "Order messages must use the saved customer and store recipients");
    const nextOrder = await createOrder({ ...input, idempotencyKey: randomUUID(), marketingOptOut: true }, "test");
    check(nextOrder.order_number === "N7-1002", "The next order increments by one and retries do not consume a number");
    check((await selectOne<RowDataPacket>("SELECT status FROM newsletter_subscribers WHERE id = ?", [softSubscriber!.id]))?.status === "UNSUBSCRIBED", "Checkout opt-out must unsubscribe an existing active customer");
    check((await job(String(softWelcomes[0].id)))?.status === "CANCELLED", "Checkout opt-out must cancel queued marketing");
    const confirmationJob = await selectOne<RowDataPacket>("SELECT status FROM email_jobs WHERE recipient = ? AND template_key = 'order-confirmation'", [input.customer.email]);
    check(confirmationJob?.status === "PENDING", "Marketing opt-out must leave order confirmations queued");
    check(await unsubscribeNewsletter(softUnsubscribeToken), "Checkout subscribers must have a working, repeatable unsubscribe link");
    await createOrder({ ...input, idempotencyKey: randomUUID() }, "test");
    check((await selectOne<RowDataPacket>("SELECT status FROM newsletter_subscribers WHERE id = ?", [softSubscriber!.id]))?.status === "UNSUBSCRIBED", "An unchecked box on a later checkout must respect the previous unsubscribe");
    await createOrder({ ...input, idempotencyKey: randomUUID(), customer: { ...input.customer, email: "new-optout@example.com" }, marketingOptOut: true }, "test");
    const newOptOut = await selectOne<RowDataPacket>("SELECT * FROM newsletter_subscribers WHERE email = 'new-optout@example.com'");
    check(newOptOut?.status === "UNSUBSCRIBED" && newOptOut.marketing_basis === null, "A new checkout opt-out must create a suppression record without marketing consent");
    check((await selectRows("SELECT id FROM email_jobs WHERE subscriber_id = ?", [newOptOut!.id])).length === 0, "An opted-out new customer must receive no subscription email");
    await createOrder({ ...input, idempotencyKey: randomUUID(), customer: { ...input.customer, email: "rate@example.com" } }, "test");
    check((await selectOne<RowDataPacket>("SELECT status FROM newsletter_subscribers WHERE email = 'rate@example.com'"))?.status === "PENDING", "Checkout must not bypass a pending newsletter confirmation");
    const withoutNotice = await createOrder({ ...input, idempotencyKey: randomUUID(), customer: { ...input.customer, email: "cart-wallet@example.com" }, marketingOptOut: undefined }, "test");
    check(!await selectOne("SELECT id FROM newsletter_subscribers WHERE email = 'cart-wallet@example.com'"), "Express checkout without a displayed notice must not subscribe the customer");
    check((await selectOne<RowDataPacket>("SELECT marketing_opt_out, marketing_preference_recorded_at FROM orders WHERE id = ?", [withoutNotice.id]))?.marketing_preference_recorded_at === null, "Missing preference must not be treated as an unchecked opt-out");
    const routing = legacyNotificationSettings("team@example.com");
    routing.defaultRecipients = ["ops@example.com", "warehouse@example.com"];
    routing.routes.order_update = { enabled: true, useDefault: false, recipients: ["updates@example.com"] };
    routing.routes.enquiry = { enabled: true, useDefault: false, recipients: ["support@example.com"] };
    routing.routes.payment_failure.enabled = true;
    routing.routes.low_stock.enabled = true;
    await saveEmailSetting("email.notifications", routing, null);
    await saveEmailSetting("email.reply_to", "replies@example.com", null);
    const routedBrand = await getEmailPreferences();
    check(routedBrand.replyToEmail === "replies@example.com", "Customer reply-to is independent of contact and notification addresses");
    await enqueueStoreNotification(routedBrand, "new_order", { ...message, templateKey: "new-order-team", replyTo: "customer@example.com" }, "routing-check");
    await enqueueStoreNotification(routedBrand, "new_order", { ...message, templateKey: "new-order-team", replyTo: "customer@example.com" }, "routing-check");
    let routedJobs = await selectRows<RowDataPacket>("SELECT * FROM email_jobs WHERE dedupe_key LIKE 'notification:new_order:routing-check:%'");
    check(routedJobs.length === 2, "Each internal recipient gets one deduplicated job");
    failRecipient = "warehouse@example.com";
    await processEmailQueue(50);
    routedJobs = await selectRows<RowDataPacket>("SELECT * FROM email_jobs WHERE dedupe_key LIKE 'notification:new_order:routing-check:%'");
    check(routedJobs.some((row) => row.recipient === "ops@example.com" && row.status === "SENT") && routedJobs.some((row) => row.recipient === failRecipient && row.status === "PENDING"), "A failed recipient does not block another recipient");
    check(delivered.some((email) => email.to === "ops@example.com" && email.replyTo === "customer@example.com"), "Team email replies go to the customer");
    failRecipient = "";
    await executeMutation("UPDATE email_jobs SET available_at = CURRENT_TIMESTAMP(3) WHERE dedupe_key LIKE 'notification:new_order:routing-check:%'");
    await processEmailQueue(50);
    check((await selectRows<RowDataPacket>("SELECT * FROM email_jobs WHERE dedupe_key LIKE 'notification:new_order:routing-check:%'")).every((row) => row.status === "SENT"), "Recipient retries recover independently");
    await withTransaction(async (connection) => enqueueOrderEmails(order.id, "update:routing-check", connection));
    check((await selectRows<RowDataPacket>("SELECT recipient FROM email_jobs WHERE template_key = 'order-update-team'")).some((row) => row.recipient === "updates@example.com"), "Order updates use the category override");
    await enqueueStoreNotification(routedBrand, "enquiry", { ...message, templateKey: "storefront-contact" }, "disabled-check");
    await enqueueStoreNotification(routedBrand, "new_order", { ...message, templateKey: "new-order-team" }, "removed-recipient-check");
    routing.routes.enquiry.enabled = false;
    routing.defaultRecipients = ["warehouse@example.com"];
    await saveEmailSetting("email.notifications", routing, null);
    const customerMessage = await enqueueEmail({ ...message, templateKey: "contact-receipt" }, { dedupeKey: "customer-receipt-independent" });
    await processEmailQueue(50);
    check((await selectOne<RowDataPacket>("SELECT status FROM email_jobs WHERE dedupe_key LIKE 'notification:enquiry:disabled-check:%'"))?.status === "CANCELLED", "Disabling an internal alert cancels its pending delivery");
    check((await selectOne<RowDataPacket>("SELECT status FROM email_jobs WHERE dedupe_key LIKE 'notification:new_order:removed-recipient-check:%' AND recipient = 'ops@example.com'"))?.status === "CANCELLED", "Removed recipients do not receive pending alerts");
    check((await job(customerMessage))?.status === "SENT", "Disabling internal alerts does not stop customer receipts");
    const failedIntent: PaymentIntentSnapshot = { ...intent("pi_email_failure", withoutNotice.id), status: "requires_payment_method", amount_received: 0 };
    await applyPaymentIntent(failedIntent, { id: "evt_email_failure_1", type: "payment_intent.payment_failed" });
    await applyPaymentIntent(failedIntent, { id: "evt_email_failure_2", type: "payment_intent.payment_failed" });
    check((await selectRows<RowDataPacket>("SELECT * FROM email_jobs WHERE template_key = 'payment-failure-team'")).length === 1, "Repeated payment failure notifications are deduplicated per checkout");
    await executeMutation("UPDATE product_variants SET stock_on_hand = 2, low_stock_threshold = 5 WHERE product_id = ?", [product!.id]);
    await Promise.all([enqueueLowStockAlerts(), enqueueLowStockAlerts()]);
    const lowStockCount = async () => (await selectRows("SELECT id FROM email_jobs WHERE template_key = 'low-stock-team'")).length;
    check(await lowStockCount() === notificationRecipients(routing, "low_stock").length, "Concurrent inventory checks produce one low-stock alert per recipient");
    await enqueueLowStockAlerts();
    check(await lowStockCount() === 1, "Low-stock alerts do not repeat on every worker check");
    await executeMutation("UPDATE product_variants SET stock_on_hand = 10 WHERE product_id = ?", [product!.id]);
    await enqueueLowStockAlerts();
    await executeMutation("UPDATE product_variants SET stock_on_hand = 2 WHERE product_id = ?", [product!.id]);
    await enqueueLowStockAlerts();
    check(await lowStockCount() === 2, "Restocking re-arms the next low-stock alert");
    const second = await createOrder({ ...input, idempotencyKey: randomUUID() }, "test");
    await setup.query("CREATE TRIGGER fail_test_email BEFORE INSERT ON email_jobs FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Mock outbox failure'");
    await assert.rejects(applyPaymentIntent(intent("pi_email_second", second.id), { id: "evt_email_second", type: "payment_intent.succeeded" })); checks++;
    const pending = await selectOne<RowDataPacket>("SELECT payment_status FROM orders WHERE id = ?", [second.id]);
    check(pending?.payment_status === "PENDING", "Payment update rolls back with its email outbox so the webhook can retry");
    await setup.query("DROP TRIGGER fail_test_email");

    const nextNumber = async () => Number((await selectOne<RowDataPacket>("SELECT next_number FROM order_number_sequence WHERE id = 1"))?.next_number);
    const beforeFailedCheckout = await nextNumber();
    await setup.query("CREATE TRIGGER fail_test_checkout BEFORE INSERT ON stripe_checkouts FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Mock checkout failure'");
    await assert.rejects(createOrder({ ...input, idempotencyKey: randomUUID(), marketingOptOut: undefined }, "test")); checks++;
    check(await nextNumber() === beforeFailedCheckout, "A rolled-back checkout does not consume an order number");
    await setup.query("DROP TRIGGER fail_test_checkout");
    await executeMutation("UPDATE product_variants SET stock_on_hand = 10 WHERE product_id = ?", [product!.id]);
    const concurrentInputs = Array.from({ length: 3 }, (_, index) => ({ ...input, idempotencyKey: randomUUID(), customer: { ...input.customer, email: `sequence-${index}@example.com` }, marketingOptOut: undefined }));
    const numberedOrders = await Promise.all(concurrentInputs.map((checkout) => createOrder(checkout, "test")));
    check(numberedOrders.map((item) => item.order_number).sort().join(",") === Array.from({ length: 3 }, (_, index) => `N7-${beforeFailedCheckout + index}`).sort().join(","), "Concurrent checkouts receive distinct consecutive order numbers");
    check((await createOrder(concurrentInputs[0], "test")).order_number === numberedOrders[0].order_number && await nextNumber() === beforeFailedCheckout + 3, "Retrying a completed checkout reuses its order number");

    const directory = path.resolve("reports/email-previews");
    await mkdir(directory, { recursive: true });
    for (const preview of emailPreviews({ appUrl: "https://n7.eluvaire.com", contactEmail: "preview@example.com" })) await writeFile(path.join(directory, `${preview.key}.html`), preview.email.html);
    console.log(`${checks} integration checks passed using mocked SMTP. Preview HTML: ${directory}`);
  } finally {
    nodemailer.createTransport = originalTransport;
    await globalThis.n7MySqlPool?.end();
    globalThis.n7MySqlPool = undefined;
    if (created) { await setup.query(`DROP DATABASE \`${database}\``); console.log("Temporary email test database removed."); }
    await setup.end();
  }
}
run().catch((error) => { console.error(error instanceof Error ? error.message : "Email integration check failed."); process.exitCode = 1; });
