import "./load-env";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { readFile, readdir } from "node:fs/promises";
import mysql, { type RowDataPacket } from "mysql2/promise";
import { getDatabaseConfig } from "../lib/env";
import { executeMutation, selectOne, selectRows } from "../lib/db/query";
import { withTransaction } from "../lib/db/transaction";
import { encryptSecret, decryptSecret } from "../lib/security/encryption";
import { defaultMetaSettings, getMetaSettings, type MetaSettings } from "../lib/meta/settings";
import { consentGranted } from "../lib/meta/consent";
import { saveConsent } from "../lib/meta/consent";
import { browserMetaPurchase, readMetaCheckoutContext, queueMetaPurchase } from "../lib/meta/orders";
import { makeMetaEvent, queueMetaEvent, resolveEventData } from "../lib/meta/events";
import { processMetaQueue } from "../lib/meta/queue";
import { createOrder } from "../lib/commerce/orders";
import { applyPaymentIntent, type PaymentIntentSnapshot } from "../lib/payments/stripe";
import type { CheckoutInput } from "../lib/commerce/validation";

async function run() {
  const config = getDatabaseConfig();
  assert.ok(["127.0.0.1", "localhost", "::1"].includes(config.host), "Checks require a local database");
  const database = `n7_meta_test_${Date.now()}`;
  assert.match(database, /^n7_meta_test_\d+$/);
  const options = { host: config.host, port: config.port, user: process.env.DB_ROOT_PASSWORD ? "root" : config.user, password: process.env.DB_ROOT_PASSWORD || config.password };
  const setup = await mysql.createConnection({ ...options, multipleStatements: true });
  const originalFetch = globalThis.fetch;
  const sent: { url: string; body: { data: { event_id: string; event_time: number; event_source_url: string; custom_data: unknown; user_data: unknown }[]; test_event_code?: string } }[] = [];
  let responseStatus = 200;
  let checks = 0;
  let created = false;
  const check = (value: unknown, message: string) => { assert.ok(value, message); checks++; };
  try {
    await setup.query(`CREATE DATABASE \`${database}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`); created = true;
    await setup.changeUser({ database });
    for (const name of (await readdir("database/migrations")).filter(name => name.endsWith(".sql")).sort()) await setup.query(await readFile(`database/migrations/${name}`, "utf8"));
    globalThis.n7MySqlPool = mysql.createPool({ ...options, database, connectionLimit: 6, supportBigNumbers: true, bigNumberStrings: true, timezone: "Z" });
    globalThis.fetch = async (url, init) => {
      assert.ok(String(url).startsWith("https://graph.facebook.com/v26.0/"));
      assert.equal(String(url).includes("access_token"), false);
      assert.equal(new Headers(init?.headers).get("authorization"), "Bearer fake-meta-token");
      sent.push({ url: String(url), body: JSON.parse(String(init?.body)) });
      return Response.json(responseStatus === 200 ? { events_received: 1 } : { error: { code: responseStatus === 503 ? 2 : 190, message: "Must never persist private@example.com or fake-meta-token", is_transient: responseStatus === 503 } }, { status: responseStatus });
    };
    const settings: MetaSettings = { ...defaultMetaSettings, pixelId: "123456789", capiTokenEncrypted: encryptSecret("fake-meta-token") };
    const save = async (s: MetaSettings) => executeMutation("UPDATE site_settings SET value_json = ? WHERE setting_key = 'meta.configuration'", [JSON.stringify(s)]);
    await save(settings);
    check(!(await getMetaSettings()).capiTokenEncrypted.includes("fake-meta-token"), "Token must be encrypted at rest");
    const consent = await saveConsent(new Request("https://n7.test"), true);
    const request = new Request("https://n7.test/api/commerce/orders", { headers: { cookie: `n7_marketing_consent=${consent}; _fbp=fb.1.1700000000000.123456`, "user-agent": "Integration test", "x-forwarded-for": "203.0.113.1" } });
    check(await consentGranted(consent), "Saved consent is granted");
    check(await readMetaCheckoutContext(new Request("https://n7.test")) === undefined, "No consent means no checkout attribution");
    const optedOut = new Request(request, { headers: { cookie: `n7_marketing_consent=${consent}; n7_marketing_optout=1` } });
    check(await readMetaCheckoutContext(optedOut) === undefined, "An immediate local opt-out overrides a stale server consent record");
    const context = await readMetaCheckoutContext(request);
    assert.ok(context);
    const product = await executeMutation("INSERT INTO products (name, slug, status, track_inventory) VALUES ('Meta test', 'meta-test', 'ACTIVE', 1)");
    const variant = await executeMutation("INSERT INTO product_variants (product_id, title, sku, price_pence, stock_on_hand, is_default) VALUES (?, '100 ml', 'META-TEST', 4500, 50, 1)", [product.insertId]);
    const zone = await executeMutation("INSERT INTO shipping_zones (name) VALUES ('UK test')");
    await executeMutation("INSERT INTO shipping_zone_countries (zone_id, country_code) VALUES (?, 'GB')", [zone.insertId]);
    const delivery = await executeMutation("INSERT INTO shipping_methods (name, method_type, price_pence) VALUES ('Delivery', 'DELIVERY', 299)");
    await executeMutation("INSERT INTO shipping_method_rates (method_id,zone_id,price_pence) VALUES (?,?,299)", [delivery.insertId, zone.insertId]);
    const address = { fullName: "Meta Test", line1: "1 Test Street", city: "London", postalCode: "SW1A 1AA", countryCode: "GB" as const, phone: "02079460000" };
    const input: CheckoutInput = { idempotencyKey: randomUUID(), expectedTotalPence: 4799, items: [{ slug: "meta-test", quantity: 1 }], customer: { name: address.fullName, email: "private@example.com", phone: address.phone }, countryCode: "GB", billingAddress: address, shippingAddress: address, paymentMethod: "STRIPE", shippingMethodId: String(delivery.insertId) };
    const paidIntent = (orderId: string, live = true): PaymentIntentSnapshot => ({ id: `pi_fixture_${orderId}`, amount: 4799, amount_received: 4799, currency: "gbp", livemode: live, status: "succeeded", metadata: { n7_order_id: orderId } });
    const order = await createOrder(input, "live", undefined, context);
    const stored = await selectOne<RowDataPacket>("SELECT payload_encrypted FROM meta_order_contexts WHERE order_id = ?", [order.id]);
    check(stored && !decryptSecret(stored.payload_encrypted).includes("private@example.com"), "Stored matching data contains hashes, not email addresses");
    await processMetaQueue(); check(sent.length === 0, "An unpaid order is never a purchase event");
    await applyPaymentIntent(paidIntent(order.id));
    await Promise.all([processMetaQueue(), processMetaQueue()]);
    check(sent.length === 1, "Concurrent workers send a paid order once");
    check(sent[0].body.data[0].event_id === `n7_purchase_${order.id}`, "Purchase event ID is stable");
    check(!sent[0].body.data[0].event_source_url.includes("?"), "Receipt tokens are absent from source URLs");
    check(JSON.stringify(sent[0].body.data[0].custom_data).includes(`n7_variant_${variant.insertId}`), "Purchase uses the same catalogue variant ID");
    const browser = await browserMetaPurchase(order.id, request);
    check(browser?.eventId === sent[0].body.data[0].event_id && browser.data.value === 47.99, "Browser and server purchase share ID and paid total including delivery");
    check(!await browserMetaPurchase(order.id, new Request("https://n7.test")), "A shared receipt is not permission to track another browser");
    await applyPaymentIntent(paidIntent(order.id)); await processMetaQueue(); check(sent.length === 1, "Webhook replays cannot create duplicate conversions");
    check((await selectOne<RowDataPacket>("SELECT payload_encrypted FROM meta_event_jobs WHERE event_name = 'Purchase'"))?.payload_encrypted === null, "Accepted payloads are removed");
    const view = await resolveEventData({ name: "ViewContent", eventId: randomUUID(), path: "/products/meta-test", items: [{ slug: "meta-test", quantity: 1 }] });
    check(view.content_ids?.[0] === browser?.data.content_ids?.[0] && view.value === 45, "View and purchase catalogue IDs match");
    await assert.rejects(resolveEventData({ name: "AddToCart", eventId: randomUUID(), path: "/", items: [{ slug: "not-found", quantity: 1 }] })); checks++;
    const retryId = randomUUID();
    const event = makeMetaEvent("AddToCart", retryId, "/products/meta-test?email=secret", { client_user_agent: "Test" }, view);
    await queueMetaEvent(event, settings, consent);
    responseStatus = 503; await processMetaQueue();
    let retry = await selectOne<RowDataPacket>("SELECT * FROM meta_event_jobs WHERE event_id = ?", [retryId]);
    check(retry?.status === "PENDING" && retry?.attempts === 1, "Transient failures back off");
    check(!String(retry?.last_error).includes("private@example.com") && !String(retry?.last_error).includes("fake-meta-token"), "Remote error text cannot leak identifiers or credentials");
    await executeMutation("UPDATE meta_event_jobs SET next_attempt_at = CURRENT_TIMESTAMP(3) WHERE event_id = ?", [retryId]);
    responseStatus = 200; await processMetaQueue();
    retry = await selectOne<RowDataPacket>("SELECT * FROM meta_event_jobs WHERE event_id = ?", [retryId]);
    check(retry?.status === "SENT" && sent.at(-1)?.body.data[0].event_time === event.event_time && sent.at(-1)?.body.data[0].event_id === retryId, "Retry preserves the event ID and actual event time");
    const testOrder = await createOrder({ ...input, idempotencyKey: randomUUID() }, "test", undefined, context);
    await applyPaymentIntent(paidIntent(testOrder.id, false));
    const before = sent.length; await processMetaQueue();
    check(sent.length === before && !await browserMetaPurchase(testOrder.id, request), "Stripe test payments never enter live reporting");
    const testSettings = { ...settings, testEventCode: "TEST123" };
    await save(testSettings);
    const testContext = await readMetaCheckoutContext(request); assert.ok(testContext);
    const testPurchase = await createOrder({ ...input, idempotencyKey: randomUUID() }, "test", undefined, testContext);
    await applyPaymentIntent(paidIntent(testPurchase.id, false)); await processMetaQueue();
    check(sent.at(-1)?.body.test_event_code === "TEST123" && !await browserMetaPurchase(testPurchase.id, request), "Test payments use CAPI Test Events only");
    await save(settings);
    const revokedId = randomUUID();
    await queueMetaEvent(makeMetaEvent("PageView", revokedId, "/", { client_user_agent: "Test" }, {}), settings, consent);
    await saveConsent(request, false);
    check(!await consentGranted(consent), "Withdrawal persists");
    check((await selectOne<RowDataPacket>("SELECT status, payload_encrypted FROM meta_event_jobs WHERE event_id = ?", [revokedId]))?.status === "CANCELLED", "Withdrawal cancels pending events");
    check((await selectRows("SELECT order_id FROM meta_order_contexts WHERE consent_id = ?", [consent])).length === 0, "Withdrawal removes pending order attribution");
    check(!await browserMetaPurchase(order.id, request), "Receipt cannot track after withdrawal");
    await withTransaction(connection => queueMetaPurchase(order.id, connection));
    const expiryId = randomUUID();
    await queueMetaEvent(makeMetaEvent("PageView", expiryId, "/", { client_user_agent: "Test" }, {}), settings, null);
    await executeMutation("UPDATE meta_event_jobs SET event_time = DATE_SUB(CURRENT_TIMESTAMP(3), INTERVAL 48 HOUR) WHERE event_id = ?", [expiryId]);
    await processMetaQueue();
    check((await selectOne<RowDataPacket>("SELECT status, payload_encrypted FROM meta_event_jobs WHERE event_id = ?", [expiryId]))?.payload_encrypted === null, "Expired events are erased instead of being sent beyond deduplication window");
    await saveConsent(request, true);
    await executeMutation("RENAME TABLE meta_order_contexts TO meta_order_contexts_unavailable");
    try {
      const untrackedOrder = await createOrder({ ...input, idempotencyKey: randomUUID() }, "live", undefined, context);
      check(Boolean(await selectOne("SELECT id FROM orders WHERE id = ?", [untrackedOrder.id])), "Tracking storage failure cannot roll back a valid order");
    } finally {
      await executeMutation("RENAME TABLE meta_order_contexts_unavailable TO meta_order_contexts");
    }
    console.log(`${checks} Meta integration checks passed; no real Meta or Stripe calls, charges or emails.`);
  } finally {
    globalThis.fetch = originalFetch;
    await globalThis.n7MySqlPool?.end(); globalThis.n7MySqlPool = undefined;
    if (created) await setup.query(`DROP DATABASE \`${database}\``);
    await setup.end();
  }
}
void run().catch(error => { console.error(error instanceof Error ? error.message : "Meta integration checks failed"); process.exitCode = 1; });
