import type { RowDataPacket } from "mysql2/promise";
import { Plus } from "lucide-react";
import CustomSelect from "@/components/admin/CustomSelect";
import Notice from "@/components/admin/Notice";
import PageHeader from "@/components/admin/PageHeader";
import { selectRows } from "@/lib/db/query";
import { createCouponAction, updateCouponAction } from "./actions";
interface CouponRow extends RowDataPacket { id: string; discount_id: string; code: string; usage_limit: number | null; per_email_limit: number | null; used_count: number; is_active: number; discount_name: string }
interface DiscountOption extends RowDataPacket { id: string; name: string }
const input = "w-full rounded-lg border border-zinc-300 bg-white px-3 py-2 text-sm outline-none focus:border-amber-700 focus:ring-2 focus:ring-amber-100";
function Fields({ item, discounts }: { item?: CouponRow; discounts: DiscountOption[] }) { return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><CustomSelect className="lg:col-span-2" defaultValue={item?.discount_id} name="discountId" options={discounts.map((discount) => ({ value: discount.id, label: discount.name }))} placeholder="Choose coupon discount" required /><input aria-label="Coupon code" className={input} defaultValue={item?.code} maxLength={80} name="code" placeholder="WELCOME10" required /><input aria-label="Usage limit" className={input} defaultValue={item?.usage_limit ?? ""} min={1} name="usageLimit" placeholder="Total limit" type="number" /><input aria-label="Per email limit" className={input} defaultValue={item?.per_email_limit ?? ""} min={1} name="perEmailLimit" placeholder="Per-email limit" type="number" /><label className="flex items-center gap-2 text-sm text-zinc-700"><input defaultChecked={item ? Boolean(item.is_active) : true} name="isActive" type="checkbox" />Active</label></div>; }
export default async function CouponsPage({ searchParams }: { searchParams: Promise<{ error?: string; saved?: string }> }) { const [items, discounts, query] = await Promise.all([selectRows<CouponRow>(`SELECT CAST(c.id AS CHAR) AS id, CAST(c.discount_id AS CHAR) AS discount_id, c.code, c.usage_limit, c.per_email_limit, c.used_count, c.is_active, d.name AS discount_name FROM coupons c INNER JOIN discounts d ON d.id = c.discount_id ORDER BY c.created_at DESC`), selectRows<DiscountOption>("SELECT CAST(id AS CHAR) AS id, name FROM discounts WHERE method = 'COUPON' ORDER BY name"), searchParams]); return <div><PageHeader eyebrow="Promotions" title="Coupons" description="Create codes and control total and per-customer usage." />{query.saved ? <Notice type="success">Coupons saved.</Notice> : null}{query.error ? <Notice>{query.error === "duplicate" ? "That coupon code is already in use." : "Check the coupon values and choose a coupon discount."}</Notice> : null}<section className="mt-7 rounded-xl border border-zinc-200 bg-white p-5 shadow-sm"><h2 className="mb-4 font-body text-base font-semibold text-zinc-950">Add coupon</h2>{discounts.length ? <form action={createCouponAction}><Fields discounts={discounts} /><button className="mt-4 inline-flex items-center gap-2 rounded-lg bg-zinc-950 px-4 py-2 text-sm font-semibold text-white" type="submit"><Plus size={15} />Add coupon</button></form> : <p className="text-sm text-zinc-500">Create a discount with the “Coupon based” method first.</p>}</section><section className="mt-5 space-y-3">{items.map((item) => <details key={item.id} className="rounded-xl border border-zinc-200 bg-white shadow-sm"><summary className="flex cursor-pointer list-none items-center gap-4 px-5 py-4"><div className="flex-1"><p className="font-mono font-semibold">{item.code}</p><p className="mt-0.5 text-xs text-zinc-400">{item.discount_name} · used {item.used_count}{item.usage_limit ? ` of ${item.usage_limit}` : " times"}</p></div><span className={`rounded-full px-2 py-1 text-xs ${item.is_active ? "bg-emerald-50 text-emerald-700" : "bg-zinc-100 text-zinc-500"}`}>{item.is_active ? "active" : "inactive"}</span></summary><form action={updateCouponAction.bind(null, item.id)} className="border-t border-zinc-100 p-5"><Fields item={item} discounts={discounts} /><button className="mt-4 rounded-lg bg-zinc-950 px-4 py-2 text-sm font-semibold text-white" type="submit">Save coupon</button></form></details>)}</section></div>; }
