import type { RowDataPacket } from "mysql2/promise";
import { Plus } from "lucide-react";
import CustomSelect from "@/components/admin/CustomSelect";
import MediaDropzone from "@/components/admin/MediaDropzone";
import Notice from "@/components/admin/Notice";
import PageHeader from "@/components/admin/PageHeader";
import StatusBadge from "@/components/admin/StatusBadge";
import { selectRows } from "@/lib/db/query";
import { createCollectionAction, updateCollectionAction } from "./actions";

interface CollectionRow extends RowDataPacket { id: string; name: string; slug: string; description: string | null; image_url: string | null; status: "DRAFT" | "ACTIVE" | "ARCHIVED"; sort_order: number; seo_title: string | null; seo_description: string | null; product_count: number }
const input = "w-full rounded-lg border border-zinc-300 bg-white px-3 py-2 text-sm outline-none focus:border-amber-700 focus:ring-2 focus:ring-amber-100";
function Fields({ item }: { item?: CollectionRow }) { return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><input aria-label="Name" className={input} defaultValue={item?.name} maxLength={150} name="name" placeholder="Collection name" required /><input aria-label="Slug" className={input} defaultValue={item?.slug} maxLength={190} name="slug" placeholder="Slug (optional)" /><CustomSelect defaultValue={item?.status ?? "DRAFT"} name="status" options={[{ value: "DRAFT", label: "Draft" }, { value: "ACTIVE", label: "Active" }, { value: "ARCHIVED", label: "Archived" }]} required searchable={false} /><input aria-label="Sort order" className={input} defaultValue={item?.sort_order ?? 0} name="sortOrder" type="number" /><MediaDropzone accept="image" className="sm:col-span-2 lg:col-span-4" defaultAssets={item?.image_url ? [{ url: item.image_url, name: item.name, type: "image" }] : []} label="Collection image" name="imageUrl" /><input aria-label="SEO title" className="sm:col-span-2 w-full rounded-lg border border-zinc-300 bg-white px-3 py-2 text-sm outline-none focus:border-amber-700 focus:ring-2 focus:ring-amber-100" defaultValue={item?.seo_title ?? ""} maxLength={190} name="seoTitle" placeholder="SEO title" /><textarea aria-label="Description" className={`${input} sm:col-span-2`} defaultValue={item?.description ?? ""} maxLength={10000} name="description" placeholder="Description" rows={3} /><textarea aria-label="SEO description" className={`${input} sm:col-span-2`} defaultValue={item?.seo_description ?? ""} maxLength={320} name="seoDescription" placeholder="SEO description" rows={3} /></div>; }
export default async function CollectionsPage({ searchParams }: { searchParams: Promise<{ error?: string; saved?: string }> }) { const [items, query] = await Promise.all([selectRows<CollectionRow>(`SELECT CAST(c.id AS CHAR) AS id, c.name, c.slug, c.description, c.image_url, c.status, c.sort_order, c.seo_title, c.seo_description, COUNT(pc.product_id) AS product_count FROM collections c LEFT JOIN product_collections pc ON pc.collection_id = c.id GROUP BY c.id ORDER BY c.sort_order, c.name`), searchParams]); return <div><PageHeader eyebrow="Catalog" title="Collections" description="Curate product groups for storefront pages and campaigns." />{query.saved ? <Notice type="success">Collections saved.</Notice> : null}{query.error ? <Notice>{query.error === "duplicate" ? "That collection slug is already in use." : "Check the collection values."}</Notice> : null}<section className="mt-7 rounded-xl border border-zinc-200 bg-white p-5 shadow-sm"><h2 className="mb-4 font-body text-base font-semibold text-zinc-950">Add collection</h2><form action={createCollectionAction}><Fields /><button className="mt-4 inline-flex items-center gap-2 rounded-lg bg-zinc-950 px-4 py-2 text-sm font-semibold text-white" type="submit"><Plus size={15} />Add collection</button></form></section><section className="mt-5 space-y-3">{items.map((item) => <details key={item.id} className="group rounded-xl border border-zinc-200 bg-white shadow-sm"><summary className="flex cursor-pointer list-none items-center gap-4 px-5 py-4"><div className="min-w-0 flex-1"><p className="truncate font-medium">{item.name}</p><p className="mt-0.5 text-xs text-zinc-400">/{item.slug} · {item.product_count} products</p></div><StatusBadge status={item.status} /><span className="text-zinc-400 group-open:rotate-180">⌄</span></summary><form action={updateCollectionAction.bind(null, item.id)} className="border-t border-zinc-100 p-5"><Fields item={item} /><button className="mt-4 rounded-lg bg-zinc-950 px-4 py-2 text-sm font-semibold text-white" type="submit">Save collection</button></form></details>)}{!items.length ? <p className="rounded-xl border border-dashed border-zinc-300 py-10 text-center text-sm text-zinc-500">No collections yet.</p> : null}</section></div>; }
